import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'te' | 'hi';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {}, // English falls back to the key itself
  te: {
    // Top banner
    "Home": "హోమ్",
    "Features": "ఫీచర్లు",
    "Courses": "కోర్సులు",
    "Portals": "పోర్టల్స్",
    "Metrics": "మెట్రిక్స్",
    "Contact": "సంప్రదించండి",
    "Get in Touch": "సంప్రదించండి",
    "Book Appointment": "అపాయింట్‌మెంట్ బుక్ చేయండి",
    "Send Message": "సందేశం పంపండి",
    "Phone": "ఫోన్",
    "Email": "ఈమెయిల్",
    "Phone Number": "ఫోన్ నంబర్",
    "Enter your mobile number": "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    "Your message has been sent successfully! Our team will contact you shortly.": "మీ సందేశం విజయవంతంగా పంపబడింది! మా బృందం త్వరలోనే మిమ్మల్ని సంప్రదిస్తుంది.",
    "Your call appointment is booked! Confirmation email has been sent.": "మీ కాల్ అపాయింట్‌మెంట్ బుక్ చేయబడింది! నిర్ధారణ ఈమెయిల్ పంపబడింది.",
    "Sign In": "సైన్ ఇన్",
    "Sign Out": "సైన్ అవుట్",
    "Get Started": "ప్రారంభించండి",
    "Academic CRM": "విద్యా CRM",
    "Unified Management Ecosystem v2.0 is Live": "ఏకీకృత నిర్వహణ పర్యావరణ వ్యవస్థ v2.0 ప్రత్యక్ష ప్రసారంలో ఉంది",
    "Empowering Education through": "ద్వారా విద్యను బలోపేతం చేయడం",
    "Intelligent Management crm": "తెలివైన నిర్వహణ CRM",
    "Connecting Administrators, Tutors, Parents, and Students into a cohesive learning workspace. View reports, compile grades, clear billing invoices, and message teachers in real-time.": "నిర్వాహకులు, ట్యూటర్లు, తల్లిదండ్రులు మరియు విద్యార్థులను ఒక సమన్వయ అభ్యాస కార్యక్షేత్రంలోకి అనుసంధానించడం. నివేదికలను వీక్షించండి, గ్రేడ్‌లను క్రోడీకరించండి, బిల్లింగ్ ఇన్‌వాయిస్‌లను క్లియర్ చేయండి మరియు నిజ సమయంలో ఉపాధ్యాయులకు సందేశం పంపండి.",
    "Start Registration Stepper": "రిజిస్ట్రేషన్ ప్రారంభించండి",
    "Access Multi-Role Dashboards": "మల్టీ-రోల్ డాష్‌బోర్డులను యాక్సెస్ చేయండి",
    "Instant Dashboard Gateway": "తక్షణ డాష్‌బోర్డ్ గేట్‌వే",
    "Jump straight into your authorized workspace dashboard with a single click. Select your role to proceed.": "ఒకే క్లిక్‌తో మీ అధీకృత వర్క్‌స్పేస్ డాష్‌బోర్డ్‌లోకి నేరుగా వెళ్లండి. కొనసాగడానికి మీ పాత్రను ఎంచుకోండి.",
    "Admin": "అడ్మిన్",
    "Tutor": "ట్యూటర్",
    "Parent": "తల్లిదండ్రులు",
    "Student": "విద్యార్థి",

    // Sub portals
    "Explore Our Live Sub-Portals": "మా లైవ్ సబ్-పోర్టల్‌లను అన్వేషించండి",
    "EduManage CRM dynamically routes layouts based on authorized account parameters. Select a client preview node to try immediately.": "EduManage CRM అధీకృత ఖాతా పారామితుల ఆధారంగా లేఅవుట్‌లను డైనమిక్‌గా రూట్ చేస్తుంది. వెంటనే ప్రయత్నించడానికి క్లయింట్ ప్రివ్యూ నోడ్‌ను ఎంచుకోండి.",
    "Administrative CRM": "పరిపాలనా CRM",
    "Manage standard student directory databases, track fee metrics, monitor real-time security audits and logs, & enroll students securely.": "ప్రామాణిక విద్యార్థి డైరెక్టరీ డేటాబేస్‌లను నిర్వహించండి, ఫీజుల కొలమానాలను ట్రాక్ చేయండి, నిజ-సమయ భద్రతా ఆడిట్లు మరియు లాగ్‌లను పర్యవేక్షించండి & విద్యార్థులను సురక్షితంగా నమోదు చేయండి.",
    "Quick Preview CRM Panel": "శీఘ్ర ప్రివ్యూ CRM ప్యానెల్",
    "Tutor Workspace": "ట్యూటర్ వర్క్‌స్పేస్",
    "Log class attendances quickly, record progress indicators, add grades to historic exams, & edit curriculum trackers with zero delay.": "క్లాస్ హాజరును త్వరగా నమోదు చేయండి, పురోగతి సూచికలను రికార్డ్ చేయండి, పరీక్షలకు గ్రేడ్‌లను జోడించండి & ఆలస్యం లేకుండా పాఠ్యప్రణాళికను సవరించండి.",
    "Launch Tutor Control": "ట్యూటర్ నియంత్రణను ప్రారంభించండి",
    "Parent Portal": "పేరెంట్ పోర్టల్",
    "Track child metrics (attendance gauges, homework grades), review notifications transcripts, pay bills & invoices via payment gateways.": "పిల్లల కొలమానాలను ట్రాక్ చేయండి (హాజరు, హోంవర్క్ గ్రేడ్‌లు), నోటిఫికేషన్ ట్రాన్స్‌క్రిప్ట్‌లను సమీక్షించండి, చెల్లింపు గేట్‌వేల ద్వారా బిల్లులు & ఇన్‌వాయిస్‌లను చెల్లించండి.",
    "Configure Parent Linkage": "పేరెంట్ లింకేజ్ కాన్ఫిగర్ చేయండి",
    "Student Portal": "స్టూడెంట్ పోర్టల్",
    "View customized curricula, monitor active homework completions, check class schedules, and simulate communication using active support channels.": "అనుకూలీకరించిన పాఠ్యప్రణాళికను వీక్షించండి, హోంవర్క్ పూర్తి చేయడాన్ని పర్యవేక్షించండి, క్లాస్ షెడ్యూల్‌లను తనిఖీ చేయండి మరియు మద్దతు ఛానెల్‌లను ఉపయోగించి కమ్యూనికేషన్‌ను అనుకరించండి.",
    "Access Learning Board": "అభ్యాస బోర్డ్‌ను యాక్సెస్ చేయండి",

    // Courses Section
    "Curated Syllabus Programs": "క్యూరేటెడ్ సిలబస్ ప్రోగ్రామ్‌లు",
    "Academic Courses Provided": "అందించే విద్యా కోర్సులు",
    "Discover our advanced, tutor-led honors courses. Click to start learning or view course specifics instantly.": "మా అధునాతన, ట్యూటర్ నేతృత్వంలోని ఆనర్స్ కోర్సులను కనుగొనండి. నేర్చుకోవడం ప్రారంభించడానికి లేదా కోర్సు వివరాలను తక్షణమే వీక్షించడానికి క్లిక్ చేయండి.",
    "Enroll Now": "ఇప్పుడే చేరండి",
    "Instructed by:": "బోధించినవారు:",

    // Features Section
    "CRM Core Capabilities": "CRM ప్రధాన సామర్థ్యాలు",
    "Engineered for Academic Precision and Operations": "విద్యాపరమైన ఖచ్చితత్వం మరియు కార్యకలాపాల కోసం రూపొందించబడింది",
    "Comprehensive Accounting": "సమగ్ర అకౌంటింగ్",
    "Seamless Payment Linkages for Outstanding Dues": "బకాయిల కోసం అతుకులు లేని చెల్లింపు లింకేజీలు",
    "Say goodbye to complicated tuition billing. Administrators issue itemized billing ledgers while parents receive real-time notifications to complete secure payment gateways instantly inside the dashboard.": "సంక్లిష్టమైన ట్యూషన్ బిల్లింగ్‌కు స్వస్తి చెప్పండి. నిర్వాహకులు ఐటమైజ్డ్ బిల్లింగ్ లెడ్జర్‌లను జారీ చేస్తారు మరియు తల్లిదండ్రులు డాష్‌బోర్డ్ లోపల సురక్షితమైన చెల్లింపు గేట్‌వేలను తక్షణమే పూర్తి చేయడానికి నిజ-సమయ నోటిఫికేషన్‌లను అందుకుంటారు.",
    "Itemized Billing": "ఐటమైజ్డ్ బిల్లింగ్",
    "Automated invoices": "స్వయంచాలక ఇన్‌వాయిస్‌లు",
    "Direct Remittance": "प्रत्यक्ष బదిలీ",
    "Real-time status transitions": "నిజ-సమయ స్థితి మార్పులు",
    "Declined Card Logs": "తిరస్కరించబడిన కార్డ్ లాగ్‌లు",
    "Admin audit trail": "అడ్మిన్ ఆడిట్ ట్రైల్",
    "Advanced Visualization": "అధునాతన విజువలైజేషన్",
    "Interactive Growth Metrics": "ఇంటరాక్టివ్ వృద్ధి కొలమానాలు",
    "Generate responsive enrollment visualizations dynamically. Admins can view seasonal registration statistics and budget statuses immediately under animated, vector SVG graphs.": "డైనమిక్‌గా ప్రతిస్పందించే నమోదు విజువలైజేషన్‌లను రూపొందించండి. నిర్వాహకులు యానిమేటెడ్, వెక్టర్ SVG గ్రాఫ్‌ల ద్వారా తక్షణమే రిజిస్ట్రేషన్ గణాంకాలు మరియు బడ్జెట్ స్థితులను వీక్షించవచ్చు.",

    // Stats Section
    "Enrolled Students": "నమోదైన విద్యార్థులు",
    "Attendance Rate": "హాజరు రేటు",
    "Certified Educators": "ధృవీకరించబడిన అధ్యాపకులు",
    "Parent Link Verification": "తల్లిదండ్రుల లింక్ ధృవీకరణ",

    // Footer
    "EduManage Academic Group LTD": "ఎడ్యుమేనేజ్ అకాడెమిక్ గ్రూప్ లిమిటెడ్",
    "EduManage CRM. Built for Next-Generation Learning Organizations. All rights reserved.": "ఎడ్యుమేనేజ్ CRM. తదుపరి తరం అభ్యాస సంస్థల కోసం నిర్మించబడింది. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",

    // Login Screen
    "Secure Portal Authorization": "సురక్షిత పోర్టల్ అధికారం",
    "Login Identifier": "లాగిన్ ఐడెంటిఫైయర్",
    "Access Token Key": "యాక్సెస్ టోకెన్ కీ",
    "Access Portal": "పోర్టల్‌ను యాక్సెస్ చేయండి",
    "Back": "వెనుకకు",
    "New to our campus?": "మా క్యాంపస్‌కు కొత్తా?",
    "Run Registration Stepper": "రిజిస్ట్రేషన్ ప్రారంభించండి",
    "Back to Home": "హోమ్‌కు తిరిగి వెళ్ళండి",
    "Administrative Control Panel": "పరిపాలనా నియంత్రణ ప్యానెల్",
    "Access audit registries, students list databases, and revenue trends.": "ఆడిట్ రిజిస్ట్రీలు, విద్యార్థుల జాబితా డేటాబేస్‌లు మరియు రాబడి ధోరణులను యాక్సెస్ చేయండి.",
    "Tutor Workspace Portal": "ట్యూటర్ వర్క్‌స్పేస్ పోర్టల్",
    "Mark attendances, review course timetables, and compile homework grades.": "హాజరును గుర్తించండి, కోర్సు టైమ్‌టేబుల్‌లను సమీక్షించండి మరియు హోంవర్క్ గ్రేడ్‌లను క్రోడీకరించండి.",
    "Parent Linkage Portal": "పేరెంట్ లింకేజ్ పోర్టల్",
    "Review Helena Thorne linking Marcus, check unpaid fees, and monitor announcements.": "హెలెనా థోర్న్ మార్కస్‌ను లింక్ చేయడాన్ని సమీక్షించండి, చెల్లించని ఫీజులను తనిఖీ చేయండి మరియు ప్రకటనలను పర్యవేక్షించండి.",
    "Student Learning CRM": "స్టూడెంట్ లెర్నింగ్ CRM",
    "Track Marcus Thorne active learning curves, complete assignments, and query tools.": "మార్కస్ థోర్న్ క్రియాశీల అభ్యాస వక్రతలను ట్రాక్ చేయండి, అసైన్‌మెంట్‌లను పూర్తి చేయండి మరియు సాధనాలను ప్రశ్నించండి.",
    "Please provide both administrative username/email and access key.": "దయచేసి అడ్మిన్ వినియోగదారు పేరు/ఈమెయిల్ మరియు యాక్సెస్ కీ రెండింటినీ అందించండి.",

    // Register Stepper
    "Step 1 of 3 • Credential Type": "3 లో 1వ దశ • ఆధారాల రకం",
    "Step 2 of 3 • Profile Registry": "3 లో 2వ దశ • ప్రొఫైల్ రిజిస్ట్రీ",
    "Step 3 of 3 • Validation Links": "3 లో 3వ దశ • ధృవీకరణ లింకులు",
    "Select Your Account Type": "మీ ఖాతా రకాన్ని ఎంచుకోండి",
    "Choose between Student or Parent role. EduManage delivers tailored boards based on selection parameters.": "విద్యార్థి లేదా తల్లిదండ్రుల పాత్రల మధ్య ఎంచుకోండి. EduManage ఎంపిక పారామితుల ఆధారంగా అనుకూలమైన బోర్డులను అందిస్తుంది.",
    "Student Portal Profile": "విద్యార్థి పోర్టల్ ప్రొఫైల్",
    "Complete assignment lists, query support tools directly, and track exam updates.": "అసైన్‌మెంట్ జాబితాలను పూర్తి చేయండి, సహాయక సాధనాలను నేరుగా ప్రశ్నించండి మరియు పరీక్ష నవీకరణలను ట్రాక్ చేయండి.",
    "Parent Guardian Link": "పేరెంట్ గార్డియన్ లింక్",
    "Monitor learning attendance metrics, verify unpaid fee balances, and review reports.": "అభ్యాస హాజరు కొలమానాలను పర్యవేక్షించండి, చెల్లించని ఫీజు బ్యాలెన్స్‌లను ధృవీకరించండి మరియు నివేదికలను సమీక్షించండి.",
    "Continue Profile Creation": "ప్రొఫైల్ సృష్టిని కొనసాగించండి",
    "Registry Profile Details": "రిజిస్ట్రీ ప్రొఫైల్ వివరాలు",
    "Provide legal identification and access keys for account verification checks.": "ఖాతా ధృవీకరణ తనిఖీల కోసం చట్టపరమైన గుర్తింపు మరియు యాక్సెస్ కీలను అందించండి.",
    "First Name": "మొదటి పేరు",
    "Last Name": "ఇంటి పేరు",
    "Contact Email Address": "ఈమెయిల్ చిరునామా",
    "Primary Phone Number": "ప్రాథమిక ఫోన్ నంబర్",
    "Grade Standard": "గ్రేడ్ ప్రమాణం",
    "Parent Mobile Contact (Optional)": "తల్లిదండ్రుల మొబైల్ నంబర్ (ఐచ్ఛికం)",
    "Learning Motivation Target": "అభ్యాస ప్రేరణ లక్ష్యం",
    "Secure Control Key Password": "సురక్షిత నియంత్రణ కీ పాస్‌వర్డ్",
    "Next: Validation Links": "తదుపరి: ధృవీకరణ లింకులు",
    "Finalize Enrollment": "నమోదును ఖరారు చేయండి",
    "Remembered login details?": "లాగిన్ వివరాలు గుర్తున్నాయా?",
    "Sign in as Demo User Instantly": "డెమో యూజర్‌గా తక్షణమే సైన్ ఇన్ చేయండి",
    "Linkage Policy Acknowledgement": "లింకేజ్ విధానం అంగీకారం",

    // Admin Dashboard
    "Admin Command Node": "అడ్మిన్ కమాండ్ నోడ్",
    "Active Students": "క్రియాశీల విద్యార్థులు",
    "Educators": "విద్యావేత్తలు",
    "Fees Receivable": "స్వీకరించవలసిన ఫీజులు",
    "Audit Records": "ఆడిట్ రికార్డులు",
    "Enrollment Growth Trend": "నమోదు వృద్ధి ధోరణి",
    "Budget Ledger Share": "బడ్జెట్ లెడ్జర్ వాటా",
    "Student Enrollment Directory": "విద్యార్థుల నమోదు డైరెక్టరీ",
    "Query name, grade, standard...": "పేరు, గ్రేడ్, ప్రమాణం వెతకండి...",
    "Enroll Student": "విద్యార్థిని నమోదు చేయండి",
    "System Security Activity Audits": "సిస్టమ్ భద్రతా కార్యాచరణ ఆడిట్లు",
    "Certified Educators On-Duty": "విధిలో ఉన్న ధృవీకృత అధ్యాపకులు",
    "Successfully enrolled": "సఫలవంతంగా నమోదు చేయబడింది",

    // Student Dashboard
    "Academic Portal": "విద్యా పోర్టల్",
    "GPA Trend": "GPA ధోరణి",
    "Welcome back, Marcus!": "తిరిగి స్వాగతం, మార్కస్!",
    "Track your curriculum progress metrics, check scheduled midterm locations, or chat with assigned tutor personnel in real-time.": "మీ పాఠ్యప్రణాళిక పురోగతి కొలమానాలను ట్రాక్ చేయండి, షెడ్యూల్ చేసిన మిడ్‌టర్మ్ స్థానాలను తనిఖీ చేయండి లేదా కేటాయించిన ట్యూటర్ సిబ్బందితో నిజ సమయంలో చాట్ చేయండి.",
    "Exams Timeline": "పరీక్షల కాలక్రమం",
    "Assessments Log": "మూల్యాంకనాల లాగ్",
    "Messaging Station": "సందేశ కేంద్రం",
    "Student Hub Academic Resources": "విద్యార్థి కేంద్రం విద్యా వనరులు",

    // Parent Dashboard
    "Guardian Link Account": "గార్డియన్ లింక్ ఖాతా",
    "Student Progress Directory: Marcus Thorne": "విద్యార్థి ప్రగతి డైరెక్టరీ: మార్కస్ థోర్న్",
    "Outstanding Balance Due": "చెల్లించవలసిన మొత్తం బకాయి",
    "Homework Completion": "హోంవర్క్ పూర్తి చేయడం",
    "Average Course Grades": "సగటు కోర్సు గ్రేడ్‌లు",
    "Itemized Tuition Billing & Fees Ledger": "ట్యూషన్ బిల్లింగ్ & ఫీజుల లెడ్జర్",
    "Pay Now": "ఇప్పుడే చెల్లించండి",
    "Advisory Board Bulletin": "సలహా బోర్డు బులెటిన్",
    "Secure Payment Gateway": "సురక్షిత చెల్లింపు గేట్‌వే",
    "Confirm & Remit Outstanding Dues": "బకాయిలను ధృవీకరించి చెల్లించండి",

    // Tutor Dashboard
    "Academic Command": "విద్యా కమాండ్",
    "Daily Command Space": "రోజువారీ కమాండ్ స్థలం",
    "Schedule seminar session": "సెమినార్ సెషన్‌ను షెడ్యూల్ చేయండి",
    "Mark Today's Classroom Attendance Roll": "నేటి తరగతి గది హాజరును నమోదు చేయండి",
    "Evaluate Assignment Draft": "అసైన్‌మెంట్ డ్రాఫ్ట్‌ను మూల్యాంకనం చేయండి",
    "Compile & Log Evaluation": "మూల్యాంకనాన్ని క్రోడీకరించి నమోదు చేయండి",
    "Lecture Timetable": "ఉపన్యాస కాలపట్టిక",

    // Subpage & Dashboard navigation translations (Telugu)
    "Back to Dashboard": "డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
    "Portal Navigation": "పోర్టల్ నావిగేషన్",
    "My Courses": "నా కోర్సులు",
    "Track your enrolled subjects and progress.": "మీరు నమోదు చేసుకున్న సబ్జెక్టులు మరియు పురోగతిని ట్రాక్ చేయండి.",
    "Assignments": "అసైన్‌మెంట్లు",
    "View pending, submitted, and graded assignments.": "పెండింగ్, సమర్పించిన మరియు గ్రేడ్ చేయబడిన అసైన్‌మెంట్‌లను వీక్షించండి.",
    "Attendance": "హాజరు",
    "View your attendance record across all subjects.": "అన్ని సబ్జెక్టులలో మీ హాజరు రికార్డును వీక్షించండి.",
    "Results & Grades": "ఫలితాలు & గ్రేడ్‌లు",
    "View exam results and academic performance.": "పరీక్ష ఫలితాలు మరియు విద్యా పనితీరును వీక్షించండి.",
    "My Profile": "నా ప్రొఫైల్",
    "View and update your student profile.": "మీ విద్యార్థి ప్రొఫైల్‌ను వీక్షించండి మరియు నవీకరించండి.",
    "Enrolled Courses": "నమోదైన కోర్సులు",
    "Avg Progress": "సగటు పురోగతి",
    "Completed": "పూర్తయింది",
    "Pending": "పెండింగ్",
    "Submitted": "సమర్పించబడింది",
    "Graded": "గ్రేడ్ చేయబడింది",
    "My Assignments": "నా అసైన్‌మెంట్లు",
    "Present Days": "హాజరైన రోజులు",
    "Absent Days": "హాజరుకాని రోజులు",
    "Monthly Attendance Log": "నెలవారీ హాజరు లాగ్",
    "Overall GPA": "మొత్తం GPA",
    "Best Subject": "ఉత్తమ సబ్జెక్ట్",
    "Class Rank": "క్లాస్ ర్యాంక్",
    "Exam Results": "పరీక్ష ఫలితాలు",
    "Child Progress": "పిల్లల పురోగతి",
    "Overall Average": "మొత్తం సగటు",
    "Academic Progress": "విద్యా పురోగతి",
    "Subject-wise performance for the current academic year.": "ప్రస్తుత విద్యా సంవత్సరానికి సబ్జెక్టుల వారీగా పనితీరు.",
    "Attendance History": "హాజరు చరిత్ర",
    "Outstanding Dues": "బకాయిలు",
    "Total Paid": "మొత్తం చెల్లించినది",
    "Next Due": "తదుపరి బకాయి",
    "Fee Ledger": "ఫీజుల లెడ్జర్",
    "Child Attendance": "పిల్లల హాజరు",
    "Notifications Registry": "నోటిఫికేషన్ల రిజిస్ట్రీ",
    "Parent Profile": "తల్లిదండ్రుల ప్రొఫైల్",
    "My Classes": "నా క్లాసులు",
    "Student Performance": "విద్యార్థి పనితీరు",
    "Total Hours": "మొత్తం గంటలు",
    "Log Class Attendance": "తరగతి హాజరును నమోదు చేయండి",
    "Student Management": "విద్యార్థుల నిర్వహణ",
    "Tutor Management": "ట్యూటర్ల నిర్వహణ",
    "Parent Management": "తల్లిదండ్రుల నిర్వహణ",
    "Fees": "ఫీజులు",
    "Reports": "నివేదికలు",
    "Settings": "సెట్టింగులు",
    "Course Catalogue": "కోర్సు కాటలాగ్",
    "Add Course": "కోర్సును జోడించండి",
    "Total Courses": "మొత్తం కోర్సులు",
    "Active Classes": "క్రియాశీల తరగతులు",
    "Next Class": "తదుపరి క్లాస్",
    "Weekly Timetable": "వారపు కాలపట్టిక",
    "Mark Attendance": "హాజరును గుర్తించండి",
    "Assignments Overview": "అసైన్‌మెంట్ల అవలోకనం",
    "Needs Attention": "శ్రద్ధ అవసరం",
    "Senior Faculty • Physics": "సీనియర్ ఫ్యాకల్టీ • ఫిజిక్స్",
    "Experience": "అనుభవం",
    "Tutors Directory": "ట్యూటర్ల డైరెక్టరీ",
    "Active Tutors": "క్రియాశీల ట్యూటర్లు",
    "On Leave": "సెలవులో ఉన్నారు",
    "Tutors Registry": "ట్యూటర్ల రిజిస్ట్రీ",
    "Tutor details": "ట్యూటర్ వివరాలు",
    "Parents Directory": "తల్లిదండ్రుల డైరెక్టరీ",
    "Manage parent accounts, contact details, and their linked children": "తల్లిదండ్రుల ఖాతాలు, సంప్రదింపు వివరాలు మరియు వారి లింక్ చేయబడిన పిల్లలను నిర్వహించండి",
    "Active Parents": "క్రియాశీల తల్లిదండ్రులు",
    "Total Outstanding": "మొత్తం బకాయి",
    "Linked Children": "లింక్ చేయబడిన పిల్లలు",
    "Add Parent": "తల్లిదండ్రులను జోడించండి",
    "Parent Details": "తల్లిదండ్రుల వివరాలు",
    "Class Schedule": "తరగతి షెడ్యూల్",
    "Attendance Log": "హాజరు లాగ్",
    "Financial Ledger": "ఆర్థిక లెడ్జర్",
    "Academic Reports": "విద్యా నివేదికలు",
    "System Preferences": "సిస్టమ్ ప్రాధాన్యతలు",
    "Save Changes": "మార్పులను సేవ్ చేయి",
    "Cancel": "రద్దు చేయి",
    "Close": "మూసివేయి",

    // AI Chatbox

    // AI Chatbox
    "Hello! I am your EduManage Support Assistant. Select a quick question below or ask me about attendance, fees, messaging, grades, or study materials.": "హలో! నేను మీ EduManage సహాయక అసిస్టెంట్‌ని. క్రింది శీఘ్ర ప్రశ్నను ఎంచుకోండి లేదా హాజరు, ఫీజులు, సందేశాలు, గ్రేడ్‌లు లేదా అధ్యయన సామగ్రి గురించి నన్ను అడగండి.",
    "📅 How to check attendance?": "📅 హాజరును ఎలా తనిఖీ చేయాలి?",
    "You can view the Attendance Calendar card on the Parent Dashboard, or under the 'Attendance Calendar' tab on the Student Dashboard. Present days are green, absent days (May 8 and May 20) are red, and weekends are grey.": "మీరు పేరెంట్ డాష్‌బోర్డ్‌లో హాజరు క్యాలెండర్ కార్డ్‌ని చూడవచ్చు లేదా స్టూడెంట్ డాష్‌బోర్డ్‌లోని 'హాజరు క్యాలెండర్' ట్యాబ్ కింద చూడవచ్చు. హాజరైన రోజులు ఆకుపచ్చగా, లేని రోజులు (మే 8 మరియు మే 20) ఎరుపు రంగులో మరియు వారాంతాలు బూడిద రంగులో ఉంటాయి.",
    "💳 How to pay tuition fees?": "💳 ట్యూషన్ ఫీజు ఎలా చెల్లించాలి?",
    "Navigate to the Tuition Billing Ledger on the Parent Dashboard. Click the 'Pay Now' button next to any pending/overdue item, enter your card details in the secure payment gateway modal, and confirm the transaction.": "పేరెంట్ డాష్‌బోర్డ్‌లోని ట్యూషన్ బిల్లింగ్ లెడ్జర్‌కి నావిగేట్ చేయండి. ఏదైనా పెండింగ్/గడువు ముగిసిన అంశం పక్కన ఉన్న 'ఇప్పుడే చెల్లించండి' బటన్‌ను క్లిక్ చేసి, సురక్షిత చెల్లింపు గేట్‌వే మోడల్‌లో మీ కార్డ్ వివరాలను నమోదు చేసి, లావాదేవీని ధృవీకరించండి.",
    "💬 How to contact my tutor?": "💬 నా ట్యూటర్‌ను ఎలా సంప్రదించాలి?",
    "Use the 'Messaging Station' on the Student Dashboard or the 'Direct Messages' tab on the Parent Dashboard. You can select your tutor from the dropdown menu and type a message to receive immediate simulated responses.": "స్టూడెంట్ డాష్‌బోర్డ్‌లోని 'సందేశ కేంద్రం' లేదా పేరెంట్ డాష్‌బోర్డ్‌లోని 'ప్రత్యక్ష సందేశాలు' ట్యాబ్‌ను ఉపయోగించండి. మీరు డ్రాప్‌డౌన్ మెను నుండి మీ ట్యూటర్‌ను ఎంచుకోవచ్చు మరియు తక్షణ ప్రతిస్పందనలను పొందడానికి సందేశాన్ని టైప్ చేయవచ్చు.",
    "📚 Where are study resources?": "📚 అధ్యయన వనరులు ఎక్కడ ఉన్నాయి?",
    "Academic materials and PDFs matching your registered courses are available under the 'Student Hub Academic Resources' section at the bottom of the Student Dashboard.": "మీరు నమోదు చేసుకున్న కోర్సులకు సరిపోయే విద్యా సామగ్రి మరియు PDFలు స్టూడెంట్ డాష్‌బోర్డ్ దిగువన ఉన్న 'విద్యార్థి కేంద్రం విద్యా వనరులు' విభాగంలో అందుబాటులో ఉన్నాయి.",
    "📝 How to view exam results?": "📝 పరీక్ష ఫలితాలను ఎలా వీక్షించాలి?",
    "Go to the Student Dashboard. Under the selector menu, check the 'Exams Timeline' tab for upcoming assessments, the 'Assessments Log' tab for instructor notes and marks, or 'Term Results' to download your final PDF report.": "స్టూడెంట్ డాష్‌బోర్డ్‌కి వెళ్లండి. సెలెక్టర్ మెను కింద, రాబోయే మూల్యాంకనాల కోసం 'పరీక్షల కాలక్రమం' ట్యాబ్, బోధకుని గమనికలు మరియు మార్కుల కోసం 'మూల్యాంకనాల లాగ్' ట్యాబ్ లేదా మీ తుది PDF నివేదికను డౌన్‌లోడ్ చేయడానికి 'టర్మ్ ఫలితాలు' తనిఖీ చేయండి.",
    "I am operating in offline mode. Please click one of the quick questions below, or try searching for keywords like 'attendance', 'fees', 'message', 'materials', or 'results'.": "నేను ఆఫ్‌లైన్ మోడ్‌లో పని చేస్తున్నాను. దయచేసి క్రింది శీఘ్ర ప్రశ్నలలో ఒకదానిపై క్లిక్ చేయండి లేదా 'హాజరు', 'ఫీజులు', 'సందేశం', 'సామగ్రి' లేదా 'ఫలితాలు' వంటి కీలక పదాల కోసం వెతకడానికి ప్రయత్నించండి.",
    "Assistant searching FAQ files...": "అసిస్టెంట్ తరచుగా అడిగే ప్రశ్నల ఫైల్‌లను వెతుకుతోంది...",
    "EduManage AI Support": "EduManage AI మద్దతు",
    "Offline Assistant": "ఆఫ్‌లైన్ అసిస్టెంట్",
    "Quick Questions": "శీఘ్ర ప్రశ్నలు",
    "Ask about attendance, fees, messaging...": "హాజరు, ఫీజులు, సందేశాల గురించి అడగండి...",

    // New Subpages keys (Telugu)
    "Current semester": "ప్రస్తుత సెమిస్టర్",
    "94% average": "94% సగటు",
    "Out of 32 students": "32 మంది విద్యార్థులలో",
    "Days Present": "హాజరైన రోజులు",
    "Days Absent": "హాజరుకాని రోజులు",
    "This month": "ఈ నెల",
    "Out of 21 school days": "21 పాఠశాల రోజులలో",
    "May 8 & May 20": "మే 8 & మే 20",
    "sessions": "సెషన్లు",
    "Due by Jun 30": "జూన్ 30 నాటికి బకాయి",
    "This academic year": "ఈ విద్యా సంవత్సరం",
    "Jul 1": "జూలై 1",
    "Quarterly tuition": "త్రైమాసిక ట్యూషన్",
    "Q1 Tuition Fee": "Q1 ట్యూషన్ ఫీజు",
    "Q2 Tuition Fee": "Q2 ట్యూషన్ ఫీజు",
    "Library & Lab Fees": "లైబ్రరీ & ల్యాబ్ ఫీజులు",
    "Q3 Tuition Fee": "Q3 ట్యూషన్ ఫీజు",
    "Due": "బకాయి",
    "Due: Jan 5": "బకాయి తేదీ: జనవరి 5",
    "Due: Apr 3": "బకాయి తేదీ: ఏప్రిల్ 3",
    "Due: Feb 15": "బకాయి తేదీ: ఫిబ్రవరి 15",
    "Due: Jun 30": "బకాయి తేదీ: జూన్ 30",
    "Pay Outstanding Balance (₹320)": "బకాయి మొత్తం చెల్లించండి (₹320)",
    "Attendance Alert": "హాజరు హెచ్చరిక",
    "Assignment Graded": "అసైన్‌మెంట్ గ్రేడ్ చేయబడింది",
    "Fee Reminder": "ఫీజు రిమైండర్",
    "Teacher Message": "ఉపాధ్యాయుల సందేశం",
    "{student} was marked absent on May 20 in Calculus BC.": "{student} కాల్క్యులస్ BCలో మే 20న హాజరు కాలేదని గుర్తించబడింది.",
    "{student} received 94% on the Chemistry Lab report.": "{student} కెమిస్ట్రీ ల్యాబ్ నివేదికలో 94% పొందారు.",
    "Q3 tuition fee of ₹320 is due by June 30.": "Q3 ట్యూషన్ ఫీజు ₹320 జూన్ 30 నాటికి చెల్లించాలి.",
    'Prof. Miller: "{student} has been doing exceptionally well in physics!"': "ప్రొఫెసర్ మిల్లర్: \"{student} ఫిజిక్స్‌లో అద్భుతంగా రాణిస్తున్నారు!\"",
    "2 days ago": "2 రోజుల క్రితం",
    "3 days ago": "3 రోజుల క్రితం",
    "5 days ago": "5 రోజుల క్రితం",
    "1 week ago": "1 వారం క్రితం",
    "Parent / Guardian": "తల్లిదండ్రులు / గార్డియన్",
    "Linked Student": "లింక్ చేయబడిన విద్యార్థి",
    "Student Grade": "విద్యార్థి గ్రేడ్",
    "11th Grade": "11వ తరగతి",
    "Track {student}'s performance across subjects.": "{student} యొక్క విద్యా పురోగతిని ట్రాక్ చేయండి.",
    "Monitor {student}'s daily attendance records.": "{student} యొక్క రోజువారీ హాజరు రికార్డులను పర్యవేక్షించండి.",
    "Across all courses": "అన్ని కోర్సులలో",
    "Course completed": "కోర్సు పూర్తయింది",
    "Advanced Physics": "అధునాతన భౌతికశాస్త్రం",
    "Calculus BC": "కాల్క్యులస్ BC",
    "Chemistry Honors": "కెమిస్ట్రీ ఆనర్స్",
    "AP Literature": "AP సాహిత్యం",
    "Quantum Mechanics": "క్వాంటం మెకానిక్స్",
    "Rotational Dynamics": "భ్రమణ గతిశాస్త్రం",
    "Organic Chemistry": "సేంద్రీయ రసాయన శాస్త్రం",
    "Quantum Dynamics": "క్వాంటం డైనమిక్స్",
    "Physics Mechanics": "భౌతికశాస్త్రం మెకానిక్స్",
    "Due Jun 10": "గడువు జూన్ 10",
    "Due Jun 12": "గడువు జూన్ 12",
    "Due Jun 6": "గడువు జూన్ 6",
    "Due this week": "ఈ వారం చెల్లించవలసినది",
    "Awaiting grades": "గ్రేడ్‌ల కోసం వేచి ఉంది",
    "This semester": "ఈ సెమిస్టర్",
    "Rotational Kinematics Essay": "భ్రమణ గతిశాస్త్ర వ్యాసం",
    "Integral Calculus Problem Set": "సమీకృత కాల్క్యులస్ సమస్యల సెట్",
    "Titration Lab Report": "టైట్రేషన్ ల్యాబ్ నివేదిక",
    "Physics": "భౌతికశాస్త్రం",
    "Chemistry": "రసాయన శాస్త్రం",
    "Out of 21 sessions": "21 సెషన్లలో",
    "sessions attended": "హాజరైన సెషన్లు",
    "Out of 4.0": "4.0 కి గాను",
    "91% average": "91% సగటు",
    "Physics Mid-Term": "భౌతికశాస్త్ర మిడ్-టర్మ్",
    "Calculus Unit Test 3": "కాల్క్యులస్ యూనిట్ టెస్ట్ 3",
    "Chemistry Lab Practical": "కెమిస్ట్రీ ల్యాబ్ ప్రాక్టికల్",
    "Literature Essay Exam": "సాహిత్య వ్యాస పరీక్ష",
    "Student • 11th Grade": "విద్యార్థి • 11వ తరగతి",
    "4 Subjects": "4 సబ్జెక్టులు",
    "#4 of 32": "32 లో 4వ",
    "Total Students": "మొత్తం విద్యార్థులు",
    "Across all sections": "అన్ని విభాగాలలో",
    "Physics – Studio Hall 2": "భౌతికశాస్త్రం – స్టూడియో హాల్ 2",
    "Monday": "సోమవారం",
    "Tuesday": "మంగళవారం",
    "Thursday": "గురువారం",
    "Studio Hall 2": "స్టూడియో హాల్ 2",
    "Lab Block 3": "ల్యాబ్ బ్లాక్ 3",
    "Studio Hall 1": "స్టూడియో హాల్ 1",
    "{count} Students": "{count} మంది విద్యార్థులు",
    "Today's Sessions": "నేటి సెషన్లు",
    "Sessions scheduled today": "ఈరోజు షెడ్యూల్ చేసిన సెషన్లు",
    "Avg Attendance": "సగటు హాజరు",
    "Last 30 days": "గత 30 రోజులు",
    "Absent Today": "ఈరోజు గైర్హాజరు",
    "Out of 20 students": "20 మంది విద్యార్థులలో",
    "Present": "హాజరు",
    "Absent": "గైర్హాజరు",
    "Active Assignments": "క్రియాశీల అసైన్‌మెంట్లు",
    "Currently assigned": "ప్రస్తుతం కేటాయించబడింది",
    "Submissions to grade": "గ్రేడ్ చేయవలసిన సమర్పణలు",
    "Graded This Week": "ఈ వారం గ్రేడ్ చేసినవి",
    "Completed evaluations": "పూర్తయిన మూల్యాంకనాలు",
    "Rotational Force Vector Essays": "భ్రమణ శక్తి వెక్టర్ వ్యాసాలు",
    "Quantum State Functions": "క్వాంటం స్థితి విధులు",
    "Electromagnetic Induction Report": "విద్యుదయస్కాంత ప్రేరణ నివేదిక",
    "Top Performer": "అగ్ర ప్రదర్శనకారుడు",
    "Average 94.5%": "సగటు 94.5%",
    "Class Average": "తరగతి సగటు",
    "All subjects": "అన్ని సబ్జెక్టులు",
    "Below 65% threshold": "65% పరిమితి కంటే తక్కువ",
    "Subject": "సబ్జెక్ట్",
    "8 Years": "8 సంవత్సరాలు",
    "28 Active": "28 మంది క్రియాశీల",
    "View your scheduled sessions and timetable.": "మీ షెడ్యూల్ చేసిన సెషన్‌లు మరియు టైమ్‌టేబుల్‌ను వీక్షించండి.",
    "Mark and track student attendance for your classes.": "మీ తరగతుల కోసం విద్యార్థుల హాజరును గుర్తించండి మరియు ట్రాక్ చేయండి.",
    "Manage assignment submissions and evaluations.": "అసైన్‌మెంట్ సమర్పణలు మరియు మూల్యాంకనాలను నిర్వహించండి.",
    "Track academic progress across your students.": "మీ విద్యార్థుల విద్యా పురోగతిని ట్రాక్ చేయండి.",
    "View and update your faculty profile details.": "మీ ఫ్యాకల్టీ ప్రొఫైల్ వివరాలను వీక్షించండి మరియు నవీకరించండి.",
    "Faculty": "ఫ్యాకల్టీ",
    "All academic courses and their assigned tutors": "అన్ని విద్యా కోర్సులు మరియు వాటి కేటాయించిన ట్యూటర్లు",
    "Course": "కోర్సు",
    "Students": "విద్యార్థులు",
    "Schedule": "షెడ్యూల్",
    "Level": "స్థాయి",
    "Status": "స్థితి",
    "Upcoming": "రాబోయే",
    "Draft": "డ్రాఫ్ట్",
    "Total Collected": "మొత్తం వసూలు చేయబడినది",
    "Outstanding": "బకాయి",
    "Total Invoices": "మొత్తం ఇన్‌వాయిస్‌లు",
    "Overdue": "గడువు ముగిసినవి",
    "{count} overdue invoice(s) require immediate attention. Total outstanding: ": "{count} గడువు ముగిసిన ఇన్‌వాయిస్(లు) తక్షణ శ్రద్ధ అవసరం. మొత్తం బకాయి: ",
    "Invoice": "ఇన్‌వాయిస్",
    "Amount": "మొత్తం",
    "Paid Date": "చెల్లించిన తేదీ",
    "Not paid": "చెల్లించలేదు",
    "Loading payment records...": "చెల్లింపు రికార్డులను లోడ్ చేస్తోంది...",
    "System Reports": "సిస్టమ్ నివేదికలు",
    "Generate and export academic, financial and operational reports.": "విద్యా, ఆర్థిక మరియు కార్యాచరణ నివేదికలను రూపొందించండి మరియు ఎగుమతి చేయండి.",
    "System Configuration": "సిస్టమ్ కాన్ఫిగరేషన్",
    "Adjust portal-wide settings, access control, and integrations.": "పోర్టల్-వ్యాప్త సెట్టింగ్‌లు, యాక్సెస్ నియంత్రణ మరియు ఇంటిగ్రేషన్‌లను సర్దుబాటు చేయండి.",
    "Course Management": "కోర్సుల నిర్వహణ",
    "Fees & Billing": "ఫీజులు & బిల్లింగ్",
    "Analytics & Reports": "విశ్లేషణలు & నివేదికలు",
    "Platform Settings": "ప్లాట్‌ఫారమ్ సెట్టింగ్‌లు",
    "View, add, edit and manage student enrollment records.": "విద్యార్థుల నమోదు రికార్డులను వీక్షించండి, జోడించండి, సవరించండి మరియు నిర్వహించండి.",
    "Manage teaching faculty, subjects, and class assignments.": "బోధనా సిబ్బందిని, సబ్జెక్టులను మరియు తరగతి అసైన్‌మెంట్‌లను నిర్వహించండి.",
    "View and manage guardian accounts linked to students.": "విద్యార్థులకు లింక్ చేయబడిన తల్లిదండ్రుల/గార్డియన్ల ఖాతాలను వీక్షించండి మరియు నిర్వహించండి.",
    "Create, assign, and manage academic courses and curricula.": "విద్యా కోర్సులు మరియు పాఠ్యప్రణాళికను సృష్టించండి, కేటాయించండి మరియు నిర్వహించండి.",
    "Track and manage tuition payments, invoices, and overdue dues.": "ట్యూషన్ చెల్లింపులు, ఇన్‌వాయిస్‌లు మరియు బకాయిలను ట్రాక్ చేయండి మరియు నిర్వహించండి.",
    "Generate performance, financial, and attendance reports.": "పనితీరు, ఆర్థిక మరియు హాజరు నివేదికలను రూపొందించండి.",
    "Configure global options, security policies, and integrations.": "గ్లోబల్ ఎంపికలు, భద్రతా విధానాలు మరియు ఇంటిగ్రేషన్‌లను కాన్ఫిగర్ చేయండి.",
    "View, add, edit, and delete guardian accounts linked to students.": "విద్యార్థులకు లింక్ చేయబడిన తల్లిదండ్రుల ఖాతాలను వీక్షించండి, జోడించండి, సవరించండి మరియు తొలగించండి.",
    "Unregistered Parents Detected": "నమోదుకాని తల్లిదండ్రులు కనుగొనబడ్డారు",
    "{count} parent phone(s) in the database have no portal account yet. Use \"Add Parent\" and enter the linked phone number to register them.": "డేటాబేస్‌లోని {count} తల్లిదండ్రుల ఫోన్ నంబర్(ల)కు ఇంకా పోర్టల్ ఖాతా లేదు. వారిని నమోదు చేయడానికి \"తల్లిదండ్రులను జోడించండి\" ఉపయోగించండి మరియు లింక్ చేసిన ఫోన్ నంబర్‌ను నమోదు చేయండి.",
    "{count} parent record(s) — click a row to view linked students": "{count} తల్లిదండ్రుల రికార్డు(లు) — లింక్ చేయబడిన విద్యార్థులను వీక్షించడానికి ఒక వరుసపై క్లిక్ చేయండి",
    "Add New Parent": "కొత్త తల్లిదండ్రులను జోడించండి",
    "Edit Parent": "తల్లిదండ్రుల వివరాలను సవరించండి",
    "Create a guardian portal account": "గార్డియన్ పోర్టల్ ఖాతాను సృష్టించండి",
    "Update guardian details": "గార్డియన్ వివరాలను నవీకరించండి",
    "First Name *": "మొదటి పేరు *",
    "Last Name *": "ఇంటి పేరు *",
    "Email Address": "ఈమెయిల్ చిరునామా",
    "Phone Number * ": "ఫోన్ నంబర్ * ",
    "used to link students": "విద్యార్థిని లింక్ చేయడానికి",
    "Auto-generated if left empty": "ఖాళీగా వదిలివేస్తే స్వయంచాలకంగా ఉత్పత్తి అవుతుంది",
    "Password *": "పాసవర్డ్ *",
    "Min. 6 characters": "కనీసం 6 అక్షరాలు",
    "Processing...": "ప్రక్రియ జరుగుతోంది...",
    "Create Parent Account": "తల్లిదండ్రుల ఖాతాను సృష్టించండి",
    "Delete Parent Account": "తల్లిదండ్రుల ఖాతాను తొలగించండి",
    "Are you sure you want to delete": "మీరు ఖచ్చితంగా తొలగించాలనుకుంటున్నారా",
    "This action cannot be undone.": "ఈ చర్యను రద్దు చేయలేము.",
    "{count} linked student(s) will lose their guardian link.": "{count} లింక్ చేయబడిన విద్యార్థి(లు) వారి గార్డియన్ లింక్‌ను కోల్పోతారు.",
    "Loading from database...": "ఆధారాల కోసం లోడ్ అవుతోంది...",
    "Failed to load data": "డేటాను లోడ్ చేయడం విఫలమైంది",
    "Retry": "మళ్లీ ప్రయత్నించండి",
    "No parent records found": "తల్లిదండ్రుల రికార్డులు కనుగొనబడ్డలేదు",
    "Add your first parent account to get started.": "ప్రారంభించడానికి మీ మొదటి తల్లిదండ్రుల ఖాతాను జోడించండి.",
    "Add First Parent": "మొదటి తల్లిదండ్రులను జోడించండి",
    "{count} student(s)": "{count} మంది విద్యార్థి(లు)",
    "{count} due": "{count} బకాయి",
    "Linked Students ({count})": "లింక్ చేయబడిన విద్యార్థులు ({count})",
    "No students currently linked to this phone number.": "ఈ ఫోన్ నంబర్‌కు ఏ విద్యార్థులూ లింక్ చేయబడలేదు.",
    "Parent account created successfully.": "తల్లిదండ్రుల ఖాతా విజయవంతంగా సృష్టించబడింది.",
    "Parent account updated successfully.": "తల్లిదండ్రుల ఖాతా విజయవంతంగా నవీకరించబడింది.",
    "Something went wrong. Please try again.": "ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    "Parent account deleted successfully.": "తల్లిదండ్రుల ఖాతా విజయవంతంగా తొలగించబడింది.",
    "Failed to delete parent.": "తల్లిదండ్రుల ఖాతాను తొలగించడం విఫలమైంది.",
    "Unregistered": "నమోదుకాని",
    "Registered": "నమోదైన",
    "Failed to load parents": "తల్లిదండ్రుల వివరాలను లోడ్ చేయడం విఫలమైంది",
    "Back to Directory": "డైరెక్టరీకి తిరిగి వెళ్లండి",
    "Edit Profile": "ప్రొఫైల్‌ను సవరించండి",
    "Delete Faculty Record": "ఫ్యాకల్టీ రికార్డును తొలగించండి",
    "Faculty Contact Phone": "ఫ్యాకల్టీ సంప్రదింపు ఫోన్",
    "Academic Subject Area": "విద్యా విషయ ప్రాంతం",
    "Primary teaching specialty honors": "ప్రాథమిక బోధనా ప్రత్యేకత గౌరవాలు",
    "Subject Honors": "విషయ గౌరవాలు",
    "Assigned Courses": "కేటాయించిన కోర్సులు",
    "Active sections listed": "క్రియాశీల విభాగాలు జాబితా చేయబాయి",
    "No courses assigned.": "కోర్సులు ఏవీ కేటాయించబడలేదు.",
    "Cumulative presence statistics": "సంచిత ఉనికి గణాంకాలు",
    "Salary Status": "జీతం స్థితి",
    "Tutor payment ledger status": "ట్యూటర్ చెల్లింపు లెడ్జర్ స్థితి",
    "Payment Status": "చెల్లింపు స్థితి",
    "Credited": "జమ చేయబడింది",
    "Active": "క్రియాశీల",
    "Inactive": "క్రియాశీలంగా లేని",
    "pending": "పెండింగ్",
    "100% On Duty": "100% విధిలో ఉన్నారు",
    "+12% vs last term": "+12% గత టర్మ్‌తో పోలిస్తే",
    "Logged": "నమోదైంది",
    "Real-Time Sync": "నిజ-సమయ సమకాలీకరణ",
    "Student registration loads across standard academic periods": "ప్రామాణిక విద్యా కాలాలలో విద్యార్థుల నమోదు లోడ్లు",
    "Primary Cohorts": "ప్రాథమిక సమూహాలు",
    "Tuition fees balance status across directory profiles": "డైరెక్టరీ ప్రొఫైల్‌లలో ట్యూషన్ ఫీజు బ్యాలెన్స్ స్థితి",
    "Total": "మొత్తం",
    "Paid (65%)": "చెల్లించినది (65%)",
    "Pending (20%)": "పెండింగ్ (20%)",
    "Overdue (15%)": "గడువు ముగిసినది (15%)",
    "New Enrollment Messages": "కొత్త నమోదు సందేశాలు",
    "Student Profile": "విద్యార్థి ప్రొఫైల్",
    "Applied Course / Subject": "దరఖాస్తు చేసుకున్న కోర్సు / సబ్జెక్ట్",
    "Student Phone": "విద్యార్థి ఫోన్",
    "Parent Phone": "తల్లిదండ్రుల ఫోన్",
    "Actions": "చర్యలు",
    "Awaiting Review": "సమీక్ష కోసం వేచి ఉంది",
    "N/A": "వర్తించదు",
    "Accept": "ఆమోదించు",
    "Decline": "తిరస్కరించు",
    "Live database enrollment and transaction transcripts": "లైవ్ డేటాబేస్ నమోదు మరియు లావాదేవీల ప్రతిలేఖనాలు",
    "Student Name": "విద్యార్థి పేరు",
    "Action Type": "చర్య రకం",
    "Detail": "వివరం",
    "Date & Time": "తేదీ & సమయం",
    "Ledger balance:": "లెడ్జర్ బ్యాలెన్స్:",
    "Student Academic Enrollment Directory": "విద్యార్థి విద్యా నమోదు డైరెక్టరీ",
    "Directly add new academic entries, edit status, or click student name to view detailed files.": "కొత్త విద్యా నమోదులను నేరుగా జోడించండి, స్థితిని సవరించండి లేదా వివరణాత్మక ఫైల్‌లను వీక్షించడానికి విద్యార్థి పేరుపై క్లిక్ చేయండి.",
    "Search name, course standard, phone...": "పేరు, కోర్సు ప్రమాణం, ఫోన్ ద్వారా వెతకండి...",
    "Add Student": "విద్యార్థిని జోడించండి",
    "Contact Phone": "సంప్రదింపు ఫోన్",
    "Linked Parent Phone": "లింక్ చేయబడిన తల్లిదండ్రుల ఫోన్",
    "Unlinked": "లింక్ చేయబడలేదు",
    "No student records match search query parameters.": "వెతికిన పారామితులకు సరిపోయే విద్యార్థి రికార్డులు ఏవీ లేవు.",
    "Certified Academic Faculty Directory": "ధృవీకరించబడిన విద్యా ఫ్యాకల్టీ డైరెక్టరీ",
    "Manage certified educators, courses assignations, or click tutor name to view detailed files.": "ధృవీకరించబడిన అధ్యాపకులను, కోర్సు కేటాయింపులను నిర్వహించండి లేదా వివరణాత్మక ఫైల్‌లను వీక్షించడానికి ట్యూటర్ పేరుపై క్లిక్ చేయండి.",
    "Add Faculty Tutor": "ఫ్యాకల్టీ ట్యూటర్‌ను జోడించండి",
    "Faculty Member": "ఫ్యాకల్టీ సభ్యుడు",
    "Primary Subject": "ప్రాథమిక సబ్జెక్ట్",
    "No tutors currently registered in database.": "ప్రస్తుతం డేటాబేస్‌లో ట్యూటర్లు ఎవరూ నమోదు కాలేదు.",
    "Edit Student Profile": "విద్యార్థి ప్రొఫైల్‌ను సవరించండి",
    "Enroll New Student": "కొత్త విద్యార్థిని నమోదు చేయండి",
    "Update registration database properties": "నమోదు డేటాబేస్ లక్షణాలను నవీకరించండి",
    "Register a new active student": "కొత్త క్రియాశీల విద్యార్థిని నమోదు చేయండి",
    "Jane": "జేన్",
    "Doe": "డో",
    "Email Address *": "ఈమెయిల్ చిరునామా *",
    "Student Phone *": "విద్యార్థి ఫోన్ *",
    "10 digit number": "10 అంకెల సంఖ్య",
    "Grade Standard *": "గ్రేడ్ ప్రమాణం *",
    "9th Grade": "9వ తరగతి",
    "10th Grade": "10వ తరగతి",
    "12th Grade": "12వ తరగతి",
    "Course Subject *": "కోర్సు సబ్జెక్ట్ *",
    "Enrollment Status *": "నమోదు స్థితి *",
    "student123": "student123",
    "Save Student Changes": "విద్యార్థి మార్పులను సేవ్ చేయండి",
    "Edit Tutor Profile": "ట్యూటర్ ప్రొఫైల్‌ను సవరించండి",
    "Register New Tutor": "కొత్త ట్యూటర్‌ను నమోదు చేయండి",
    "Update academic faculty database records": "విద్యా ఫ్యాకల్టీ డేటాబేస్ రికార్డులను నవీకరించండి",
    "Introduce a new certified educator": "కొత్త ధృవీకరించబడిన విద్యావేత్తను పరిచయం చేయండి",
    "Albert": "ఆల్బర్ట్",
    "Einstein": "ఐన్‌స్టీన్",
    "Subject Specialty *": "సబ్జెక్ట్ ప్రత్యేకత *",
    "Relativity & Cosmology": "సాపేక్షత & కాస్మోలజీ",
    "Experience *": "అనుభవం *",
    "e.g. 12 years": "ఉదా. 12 సంవత్సరాలు",
    "Duty Status *": "విధి స్థితి *",
    "e.g. 96%": "ఉదా. 96%",
    "tutor123": "tutor123",
    "Save Tutor Changes": "ట్యూటర్ మార్పులను సేవ్ చేయండి",
    "Register Tutor": "ట్యూటర్‌ను నమోదు చేయండి",
    "First name, last name, and student phone are required.": "మొదటి పేరు, ఇంటి పేరు మరియు విద్యార్థి ఫోన్ అవసరం.",
    "Student phone number must be exactly 10 digits.": "విద్యార్థి ఫోన్ నంబర్ ఖచ్చితంగా 10 అంకెలు ఉండాలి.",
    "Parent phone number must be exactly 10 digits.": "తల్లిదండ్రుల ఫోన్ నంబర్ ఖచ్చితంగా 10 అంకెలు ఉండాలి.",
    "Password is required.": "పాస్‌వర్డ్ అవసరం.",
    "Successfully updated student {name}": "విద్యార్థి {name} విజయవంతంగా నవీకరించబడింది",
    "Successfully enrolled student {name}": "విద్యార్థి {name} విజయవంతంగా నమోదు చేయబడింది",
    "Operation failed.": "చర్య విఫలమైంది.",
    "First name, last name, email, and tutor phone are required.": "మొదటి పేరు, ఇంటి పేరు, ఈమెయిల్ మరియు ట్యూటర్ ఫోన్ అవసరం.",
    "Tutor phone number must be exactly 10 digits.": "ట్యూటర్ ఫోన్ నంబర్ ఖచ్చితంగా 10 అంకెలు ఉండాలి.",
    "Successfully updated tutor Prof. {first} {last}": "ట్యూటర్ ప్రొఫెసర్ {first} {last} విజయవంతంగా నవీకరించబడింది",
    "Successfully added tutor Prof. {first} {last}": "ట్యూటర్ ప్రొఫెసర్ {first} {last} విజయవంతంగా జోడించబడింది",
    "Are you sure you want to delete student {name}? This will permanently remove their profile and bills.": "మీరు ఖచ్చితంగా విద్యార్థి {name}ను తొలగించాలనుకుంటున్నారా? ఇది వారి ప్రొఫైల్ మరియు బిల్లులను శాశ్వతంగా తొలగిస్తుంది.",
    "Deleted student {name}": "విద్యార్థి {name} తొలగించబడింది",
    "Delete student failed.": "విద్యార్థిని తొలగించడం విఫలమైంది.",
    "Are you sure you want to delete tutor {name}? This will permanently remove their profile.": "మీరు ఖచ్చితంగా ట్యూటర్ {name}ను తొలగించాలనుకుంటున్నారా? ఇది వారి ప్రొఫైల్‌ను శాశ్వతంగా తొలగిస్తుంది.",
    "Deleted tutor {name}": "ట్యూటర్ {name} తొలగించబడింది",
    "Delete tutor failed.": "ట్యూటర్‌ను తొలగించడం విఫలమైంది.",
    "Failed to fetch student details.": "విద్యార్థి వివరాలను పొందడం విఫలమైంది.",
    "Failed to fetch tutor details.": "ట్యూటర్ వివరాలను పొందడం విఫలమైంది.",
    "Are you sure you want to decline and delete {name}'s registry?": "మీరు ఖచ్చితంగా {name} నమోదును తిరస్కరించి, తొలగించాలనుకుంటున్నారా?",
    "Declined {name}": "{name} నమోదు తిరస్కరించబడింది",
    "Decline failed.": "తిరస్కరణ విఫలమైంది."
  },
  hi: {
    // Top banner
    "Home": "होम",
    "Features": "विशेषताएं",
    "Courses": "पाठ्यक्रम",
    "Portals": "पोर्टल",
    "Metrics": "आँकड़े",
    "Contact": "संपर्क",
    "Get in Touch": "संपर्क में रहें",
    "Book Appointment": "अपॉइंटमेंट बुक करें",
    "Send Message": "संदेश भेजें",
    "Phone": "फ़ोन",
    "Email": "ईमेल",
    "Phone Number": "फ़ोन नंबर",
    "Enter your mobile number": "अपना मोबाइल नंबर दर्ज करें",
    "Your message has been sent successfully! Our team will contact you shortly.": "आपका संदेश सफलतापूर्वक भेज दिया गया है! हमारी टीम जल्द ही आपसे संपर्क करेगी।",
    "Your call appointment is booked! Confirmation email has been sent.": "आपका कॉल अपॉइंटमेंट बुक हो गया है! पुष्टिकरण ईमेल भेज दिया गया है।",
    "Sign In": "साइन इन",
    "Sign Out": "साइन आउट",
    "Get Started": "शुरू करें",
    "Academic CRM": "शैक्षणिक सीआरएम",
    "Unified Management Ecosystem v2.0 is Live": "एकीकृत प्रबंधन पारिस्थितिकी तंत्र v2.0 लाइव है",
    "Empowering Education through": "के माध्यम से शिक्षा को सशक्त बनाना",
    "Intelligent Management crm": "इंटेलिजेंट मैनेजमेंट सीआरएम",
    "Connecting Administrators, Tutors, Parents, and Students into a cohesive learning workspace. View reports, compile grades, clear billing invoices, and message teachers in real-time.": "प्रशासकों, ट्यूटर्स, अभिभावकों और छात्रों को एक सामंजस्यपूर्ण शिक्षण कार्यक्षेत्र में जोड़ना। वास्तविक समय में रिपोर्ट देखें, ग्रेड संकलित करें, बिलिंग चालान साफ़ करें और शिक्षकों को संदेश भेजें।",
    "Start Registration Stepper": "पंजीकरण शुरू करें",
    "Access Multi-Role Dashboards": "मल्टी-रोल डैशबोर्ड एक्सेस करें",
    "Instant Dashboard Gateway": "त्वरित डैशबोर्ड गेटवे",
    "Jump straight into your authorized workspace dashboard with a single click. Select your role to proceed.": "एक क्लिक के साथ सीधे अपने अधिकृत कार्यक्षेत्र डैशबोर्ड में जाएं। आगे बढ़ने के लिए अपनी भूमिका चुनें।",
    "Admin": "एडमिन",
    "Tutor": "शिक्षक",
    "Parent": "अभिभावक",
    "Student": "छात्र",

    // Sub portals
    "Explore Our Live Sub-Portals": "हमारे लाइव सब-पोर्टल देखें",
    "EduManage CRM dynamically routes layouts based on authorized account parameters. Select a client preview node to try immediately.": "एडुमैनेज सीआरएम अधिकृत खाता मापदंडों के आधार पर लेआउट को गतिशील रूप से रूट करता है। तुरंत प्रयास करने के लिए क्लाइंट पूर्वावलोकन नोड का चयन करें।",
    "Administrative CRM": "प्रशासनिक सीआरएम",
    "Manage standard student directory databases, track fee metrics, monitor real-time security audits and logs, & enroll students securely.": "मानक छात्र निर्देशिका डेटाबेस प्रबंधित करें, शुल्क मेट्रिक्स ट्रैक करें, वास्तविक समय सुरक्षा ऑडिट और लॉग की निगरानी करें, और छात्रों को सुरक्षित रूप से नामांकित करें।",
    "Quick Preview CRM Panel": "त्वरित पूर्वावलोकन सीआरएम पैनल",
    "Tutor Workspace": "शिक्षक कार्यक्षेत्र",
    "Log class attendances quickly, record progress indicators, add grades to historic exams, & edit curriculum trackers with zero delay.": "कक्षा की उपस्थिति जल्दी दर्ज करें, प्रगति संकेतक रिकॉर्ड करें, ऐतिहासिक परीक्षाओं में ग्रेड जोड़ें, और बिना किसी देरी के पाठ्यक्रम ट्रैकर्स को संपादित करें।",
    "Launch Tutor Control": "शिक्षक नियंत्रण शुरू करें",
    "Parent Portal": "अभिभावक पोर्टल",
    "Track child metrics (attendance gauges, homework grades), review notifications transcripts, pay bills & invoices via payment gateways.": "बच्चे के मेट्रिक्स ट्रैक करें (उपस्थिति, होमवर्क ग्रेड), अधिसूचनाओं की समीक्षा करें, भुगतान गेटवे के माध्यम से बिल और चालान का भुगतान करें।",
    "Configure Parent Linkage": "अभिभावक लिंक कॉन्फ़िगर करें",
    "Student Portal": "छात्र पोर्टल",
    "View customized curricula, monitor active homework completions, check class schedules, and simulate communication using active support channels.": "अनुकूलित पाठ्यक्रम देखें, सक्रिय होमवर्क पूरा करने की निगरानी करें, कक्षा के कार्यक्रम की जांच करें, और सहायता चैनलों का उपयोग करके संचार का अनुकरण करें।",
    "Access Learning Board": "लर्निंग बोर्ड एक्सेस करें",

    // Courses Section
    "Curated Syllabus Programs": "क्यूरेटेड पाठ्यक्रम कार्यक्रम",
    "Academic Courses Provided": "प्रदान किए गए शैक्षणिक पाठ्यक्रम",
    "Discover our advanced, tutor-led honors courses. Click to start learning or view course specifics instantly.": "हमारे उन्नत, ट्यूटर-नेतृत्व वाले ऑनर्स पाठ्यक्रमों की खोज करें। सीखना शुरू करने या पाठ्यक्रम विवरण तुरंत देखने के लिए क्लिक करें।",
    "Enroll Now": "अभी नामांकन करें",
    "Instructed by:": "द्वारा निर्देशित:",

    // Features Section
    "CRM Core Capabilities": "सीआरएम मुख्य क्षमताएं",
    "Engineered for Academic Precision and Operations": "शैक्षणिक सटीकता और संचालन के लिए इंजीनियर किया गया",
    "Comprehensive Accounting": "व्यापक लेखांकन",
    "Seamless Payment Linkages for Outstanding Dues": "बकाया राशि के लिए निर्बाध भुगतान लिंक",
    "Say goodbye to complicated tuition billing. Administrators issue itemized billing ledgers while parents receive real-time notifications to complete secure payment gateways instantly inside the dashboard.": "जटिल ट्यूशन बिलिंग को अलविदा कहें। व्यवस्थापक विस्तृत बिलिंग बहीखाता जारी करते हैं जबकि माता-पिता डैशबोर्ड के अंदर सुरक्षित भुगतान गेटवे को तुरंत पूरा करने के लिए वास्तविक समय में सूचनाएं प्राप्त करते हैं।",
    "Itemized Billing": "मदवार बिलिंग",
    "Automated invoices": "स्वचालित चालान",
    "Direct Remittance": "सीधा प्रेषण",
    "Real-time status transitions": "वास्तविक समय स्थिति परिवर्तन",
    "Declined Card Logs": "अस्वीकृत कार्ड लॉग",
    "Admin audit trail": "व्यवस्थापक ऑडिट ट्रेल",
    "Advanced Visualization": "उन्नत विज़ुअलाइज़ेशन",
    "Interactive Growth Metrics": "इंटरैक्टिव विकास आँकड़े",
    "Generate responsive enrollment visualizations dynamically. Admins can view seasonal registration statistics and budget statuses immediately under animated, vector SVG graphs.": "गतिशील रूप से उत्तरदायी नामांकन विज़ुअलाइज़ेशन उत्पन्न करें। एडमिन एनिमेटेड, वेक्टर एसवीजी ग्राफ़ के तहत मौसमी पंजीकरण आंकड़े और बजट की स्थिति तुरंत देख सकते हैं।",

    // Stats Section
    "Enrolled Students": "नामांकित छात्र",
    "Attendance Rate": "उपस्थिति दर",
    "Certified Educators": "प्रमाणित शिक्षक",
    "Parent Link Verification": "अभिभावक लिंक सत्यापन",

    // Footer
    "EduManage Academic Group LTD": "एडुमैनेज एकेडमिक ग्रुप लिमिटेड",
    "EduManage CRM. Built for Next-Generation Learning Organizations. All rights reserved.": "एडुमैनेज सीआरएम। अगली पीढ़ी के शिक्षण संगठनों के लिए निर्मित। सभी अधिकार सुरक्षित।",

    // Login Screen
    "Secure Portal Authorization": "सुरक्षित पोर्टल प्राधिकरण",
    "Login Identifier": "लॉगिन पहचानकर्ता",
    "Access Token Key": "एक्सेस टोकन कुंजी",
    "Access Portal": "पोर्टल एक्सेस करें",
    "Back": "वापस",
    "New to our campus?": "हमारे परिसर में नए हैं?",
    "Run Registration Stepper": "पंजीकरण शुरू करें",
    "Back to Home": "होम पर वापस जाएं",
    "Administrative Control Panel": "प्रशासनिक नियंत्रण कक्ष",
    "Access audit registries, students list databases, and revenue trends.": "ऑडिट रजिस्ट्रियों, छात्रों की सूची डेटाबेस और राजस्व प्रवृत्तियों तक पहुंचें।",
    "Tutor Workspace Portal": "ट्यूटर कार्यक्षेत्र पोर्टल",
    "Mark attendances, review course timetables, and compile homework grades.": "उपस्थिति दर्ज करें, पाठ्यक्रम समय सारिणी की समीक्षा करें, और होमवर्क ग्रेड संकलित करें।",
    "Parent Linkage Portal": "अभिभावक लिंक पोर्टल",
    "Review Helena Thorne linking Marcus, check unpaid fees, and monitor announcements.": "हेलेना थॉर्न द्वारा मार्कस को लिंक करने की समीक्षा करें, भुगतान न की गई फीस की जांच करें और घोषणाओं की निगरानी करें।",
    "Student Learning CRM": "छात्र शिक्षण सीआरएम",
    "Track Marcus Thorne active learning curves, complete assignments, and query tools.": "मार्कस थॉर्न के सक्रिय शिक्षण वक्रों को ट्रैक करें, असाइनमेंट पूरा करें और टूल से पूछताछ करें।",
    "Please provide both administrative username/email and access key.": "कृपया प्रशासनिक उपयोगकर्ता नाम/ईमेल और एक्सेस कुंजी दोनों प्रदान करें।",

    // Register Stepper
    "Step 1 of 3 • Credential Type": "3 में से चरण 1 • क्रेडेंशियल प्रकार",
    "Step 2 of 3 • Profile Registry": "3 में से चरण 2 • प्रोफ़ाइल रजिस्ट्री",
    "Step 3 of 3 • Validation Links": "3 में से चरण 3 • सत्यापन लिंक",
    "Select Your Account Type": "अपने खाते का प्रकार चुनें",
    "Choose between Student or Parent role. EduManage delivers tailored boards based on selection parameters.": "छात्र या अभिभावक की भूमिका के बीच चयन करें। EduManage चयन मापदंडों के आधार पर अनुकूलित बोर्ड प्रदान करता है।",
    "Student Portal Profile": "छात्र पोर्टल प्रोफ़ाइल",
    "Complete assignment lists, query support tools directly, and track exam updates.": "असाइनमेंट सूचियों को पूरा करें, सीधे सहायता टूल से पूछताछ करें, और परीक्षा अपडेट ट्रैक करें।",
    "Parent Guardian Link": "अभिभावक संरक्षक लिंक",
    "Monitor learning attendance metrics, verify unpaid fee balances, and review reports.": "शिक्षण उपस्थिति मेट्रिक्स की निगरानी करें, भुगतान न किए गए शुल्क शेष को सत्यापित करें और रिपोर्ट की समीक्षा करें।",
    "Continue Profile Creation": "प्रोफ़ाइल निर्माण जारी रखें",
    "Registry Profile Details": "रजिस्ट्री प्रोफ़ाइल विवरण",
    "Provide legal identification and access keys for account verification checks.": "खाता सत्यापन जांच के लिए कानूनी पहचान और एक्सेस कुंजी प्रदान करें.",
    "First Name": "पहला नाम",
    "Last Name": "उपनाम",
    "Contact Email Address": "संपर्क ईमेल पता",
    "Primary Phone Number": "प्राथमिक फ़ोन नंबर",
    "Grade Standard": "ग्रेड मानक",
    "Parent Mobile Contact (Optional)": "अभिभावक मोबाइल संपर्क (वैकल्पिक)",
    "Learning Motivation Target": "सीखने की प्रेरणा का लक्ष्य",
    "Secure Control Key Password": "सुरक्षित नियंत्रण कुंजी पासवर्ड",
    "Next: Validation Links": "अगला: सत्यापन लिंक",
    "Finalize Enrollment": "नामांकन को अंतिम रूप दें",
    "Remembered login details?": "लॉगिन विवरण याद हैं?",
    "Sign in as Demo User Instantly": "डेमो उपयोगकर्ता के रूप में तुरंत साइन इन करें",
    "Linkage Policy Acknowledgement": "लिंकेज नीति स्वीकृति",

    // Admin Dashboard
    "Admin Command Node": "एडमिन कमांड नोड",
    "Active Students": "सक्रिय छात्र",
    "Educators": "शिक्षक",
    "Fees Receivable": "प्राप्य शुल्क",
    "Audit Records": "ऑडिट रिकॉर्ड",
    "Enrollment Growth Trend": "नामांकन वृद्धि की प्रवृत्ति",
    "Budget Ledger Share": "बजट बहीखाता हिस्सा",
    "Student Enrollment Directory": "छात्र नामांकन निर्देशिका",
    "Query name, grade, standard...": "नाम, ग्रेड, मानक खोजें...",
    "Enroll Student": "छात्र का नामांकन करें",
    "System Security Activity Audits": "सिस्टम सुरक्षा गतिविधि ऑडिट",
    "Certified Educators On-Duty": "ड्यूटी पर प्रमाणित शिक्षक",
    "Successfully enrolled": "सफलतापूर्वक नामांकित",

    // Student Dashboard
    "Academic Portal": "शैक्षणिक पोर्टल",
    "GPA Trend": "जीपीए ट्रेंड",
    "Welcome back, Marcus!": "स्वागत है, मार्कस!",
    "Track your curriculum progress metrics, check scheduled midterm locations, or chat with assigned tutor personnel in real-time.": "अपने पाठ्यक्रम प्रगति मेट्रिक्स को ट्रैक करें, निर्धारित मध्यावधि स्थानों की जांच करें, या वास्तविक समय में सौंपे गए ट्यूटर कर्मियों के साथ चैट करें।",
    "Exams Timeline": "परीक्षा समयरेखा",
    "Assessments Log": "मूल्यांकन लॉग",
    "Messaging Station": "संदेश स्टेशन",
    "Student Hub Academic Resources": "छात्र केंद्र शैक्षणिक संसाधन",

    // Parent Dashboard
    "Guardian Link Account": "अभिभावक लिंक खाता",
    "Student Progress Directory: Marcus Thorne": "छात्र प्रगति निर्देशिका: मार्कस थॉर्न",
    "Outstanding Balance Due": "बकाया राशि देय",
    "Homework Completion": "होमवर्क पूरा होना",
    "Average Course Grades": "औसत पाठ्यक्रम ग्रेड",
    "Itemized Tuition Billing & Fees Ledger": "विस्तृत ट्यूशन बिलिंग और शुल्क बहीखाता",
    "Pay Now": "अभी भुगतान करें",
    "Advisory Board Bulletin": "सलाहकार बोर्ड बुलेटिन",
    "Secure Payment Gateway": "सुरक्षित भुगतान गेटवे",
    "Confirm & Remit Outstanding Dues": "बकाया राशि की पुष्टि करें और भुगतान करें",

    // Tutor Dashboard
    "Academic Command": "शैक्षणिक कमान",
    "Daily Command Space": "दैनिक कमान क्षेत्र",
    "Schedule seminar session": "सेमिनार सत्र निर्धारित करें",
    "Mark Today's Classroom Attendance Roll": "आज की कक्षा उपस्थिति दर्ज करें",
    "Evaluate Assignment Draft": "असाइनमेंट ड्राफ्ट का मूल्यांकन करें",
    "Compile & Log Evaluation": "मूल्यांकन संकलित और दर्ज करें",
    "Lecture Timetable": "व्याख्यान समय सारिणी",

    // Subpage & Dashboard navigation translations (Hindi)
    "Back to Dashboard": "डैशबोर्ड पर वापस जाएं",
    "Portal Navigation": "पोर्टल नेविगेशन",
    "My Courses": "मेरे पाठ्यक्रम",
    "Track your enrolled subjects and progress.": "अपने नामांकित विषयों और प्रगति को ट्रैक करें।",
    "Assignments": "असाइनमेंट",
    "View pending, submitted, and graded assignments.": "लंबित, सबमिट किए गए और श्रेणीबद्ध असाइनमेंट देखें।",
    "Attendance": "उपस्थिति",
    "View your attendance record across all subjects.": "सभी विषयों में अपना उपस्थिति रिकॉर्ड देखें।",
    "Results & Grades": "परिणाम और ग्रेड",
    "View exam results and academic performance.": "परीक्षा परिणाम और शैक्षणिक प्रदर्शन देखें।",
    "My Profile": "मेरी प्रोफ़ाइल",
    "View and update your student profile.": "अपनी छात्र प्रोफ़ाइल देखें और अपडेट करें।",
    "Enrolled Courses": "नामांकित पाठ्यक्रम",
    "Avg Progress": "औसत प्रगति",
    "Completed": "पूरा हुआ",
    "Pending": "लंबित",
    "Submitted": "सबमिट किया गया",
    "Graded": "श्रेणीबद्ध",
    "My Assignments": "मेरे असाइनमेंट",
    "Present Days": "उपस्थित दिन",
    "Absent Days": "अनुपस्थित दिन",
    "Monthly Attendance Log": "मासिक उपस्थिति लॉग",
    "Overall GPA": "कुल जीपीए",
    "Best Subject": "सर्वश्रेष्ठ विषय",
    "Class Rank": "कक्षा रैंक",
    "Exam Results": "परीक्षा के परिणाम",
    "Child Progress": "बच्चे की प्रगति",
    "Overall Average": "कुल औसत",
    "Academic Progress": "शैक्षणिक प्रगति",
    "Subject-wise performance for the current academic year.": "वर्तमान शैक्षणिक वर्ष के लिए विषय-वार प्रदर्शन।",
    "Attendance History": "उपस्थिति इतिहास",
    "Outstanding Dues": "बकाया राशि",
    "Total Paid": "कुल भुगतान",
    "Next Due": "अगला बकाया",
    "Fee Ledger": "शुल्क बहीखाता",
    "Child Attendance": "बच्चे की उपस्थिति",
    "Notifications Registry": "अधिसूचना रजिस्ट्री",
    "Parent Profile": "अभिभावक प्रोफ़ाइल",
    "My Classes": "मेरी कक्षाएं",
    "Student Performance": "छात्र प्रदर्शन",
    "Total Hours": "कुल घंटे",
    "Log Class Attendance": "कक्षा की उपस्थिति दर्ज करें",
    "Student Management": "छात्र प्रबंधन",
    "Tutor Management": "शिक्षक प्रबंधन",
    "Parent Management": "अभिभावक प्रबंधन",
    "Fees": "शुल्क",
    "Reports": "रिपोर्ट",
    "Settings": "सेटिंग्स",
    "Course Catalogue": "पाठ्यक्रम सूची",
    "Add Course": "पाठ्यक्रम जोड़ें",
    "Total Courses": "कुल पाठ्यक्रम",
    "Active Classes": "सक्रिय कक्षाएं",
    "Next Class": "अगली कक्षा",
    "Weekly Timetable": "साप्ताहिक समय सारिणी",
    "Mark Attendance": "उपस्थिति दर्ज करें",
    "Assignments Overview": "असाइनमेंट अवलोकन",
    "Needs Attention": "ध्यान देने की आवश्यकता है",
    "Senior Faculty • Physics": "वरिष्ठ संकाय • भौतिकी",
    "Experience": "अनुभव",
    "Tutors Directory": "शिक्षकों की निर्देशिका",
    "Active Tutors": "सक्रिय शिक्षक",
    "On Leave": "छुट्टी पर",
    "Tutors Registry": "शिक्षक रजिस्ट्री",
    "Tutor details": "शिक्षक विवरण",
    "Parents Directory": "अभिभावकों की निर्देशिका",
    "Manage parent accounts, contact details, and their linked children": "अभिभावक खातों, संपर्क विवरण और उनके लिंक किए गए बच्चों को प्रबंधित करें",
    "Active Parents": "सक्रिय अभिभावक",
    "Total Outstanding": "कुल बकाया",
    "Linked Children": "लिंक किए गए बच्चे",
    "Add Parent": "अभिभावक जोड़ें",
    "Parent Details": "अभावक विवरण",
    "Class Schedule": "कक्षा अनुसूची",
    "Attendance Log": "उपस्थिति लॉग",
    "Financial Ledger": "वित्तीय बहीखाता",
    "Academic Reports": "शैक्षणिक रिपोर्ट",
    "System Preferences": "सिस्टम प्राथमिकताएं",
    "Save Changes": "बदलाव सहेजें",
    "Cancel": "रद्द करें",
    "Close": "बंद करें",

    // AI Chatbox

    // AI Chatbox
    "Hello! I am your EduManage Support Assistant. Select a quick question below or ask me about attendance, fees, messaging, grades, or study materials.": "नमस्ते! मैं आपका एडुमैनेज सहायता सहायक हूँ। नीचे एक त्वरित प्रश्न चुनें या मुझसे उपस्थिति, शुल्क, संदेश, ग्रेड या अध्ययन सामग्री के बारे में पूछें।",
    "📅 How to check attendance?": "📅 उपस्थिति की जांच कैसे करें?",
    "You can view the Attendance Calendar card on the Parent Dashboard, or under the 'Attendance Calendar' tab on the Student Dashboard. Present days are green, absent days (May 8 and May 20) are red, and weekends are grey.": "आप अभिभावक डैशबोर्ड पर उपस्थिति कैलेंडर कार्ड देख सकते हैं, या छात्र डैशबोर्ड पर 'उपस्थिति कैलेंडर' टैब के तहत देख सकते हैं। उपस्थित दिन हरे हैं, अनुपस्थित दिन (8 मई और 20 मई) लाल हैं, और सप्ताहांत भूरे रंग के हैं।",
    "💳 How to pay tuition fees?": "💳 ट्यूशन फीस का भुगतान कैसे करें?",
    "Navigate to the Tuition Billing Ledger on the Parent Dashboard. Click the 'Pay Now' button next to any pending/overdue item, enter your card details in the secure payment gateway modal, and confirm the transaction.": "अभिभावक डैशबोर्ड पर ट्यूशन बिलिंग बहीखाता पर जाएं। किसी भी लंबित/बकाया आइटम के बगल में 'अभी भुगतान करें' बटन पर क्लिक करें, सुरक्षित भुगतान गेटवे पॉप-अप में अपने कार्ड का विवरण दर्ज करें और लेनदेन की पुष्टि करें।",
    "💬 How to contact my tutor?": "💬 अपने ट्यूटर से कैसे संपर्क करें?",
    "Use the 'Messaging Station' on the Student Dashboard or the 'Direct Messages' tab on the Parent Dashboard. You can select your tutor from the dropdown menu and type a message to receive immediate simulated responses.": "छात्र डैशबोर्ड पर 'संदेह स्टेशन' या अभिभावक डैशबोर्ड पर 'सीधे संदेश' टैब का उपयोग करें। आप ड्रॉपडाउन मेनू से अपने ट्यूटर का चयन कर सकते हैं और त्वरित प्रतिक्रिया प्राप्त करने के लिए संदेश टाइप कर सकते हैं।",
    "📚 Where are study resources?": "📚 अध्ययन संसाधन कहाँ हैं?",
    "Academic materials and PDFs matching your registered courses are available under the 'Student Hub Academic Resources' section at the bottom of the Student Dashboard.": "आपके पंजीकृत पाठ्यक्रमों से मेल खाने वाली शैक्षणिक सामग्री और पीडीएफ छात्र डैशबोर्ड के निचले भाग में 'छात्र केंद्र शैक्षणिक संसाधन' अनुभाग के तहत उपलब्ध हैं।",
    "📝 How to view exam results?": "📝 परीक्षा परिणाम कैसे देखें?",
    "Go to the Student Dashboard. Under the selector menu, check the 'Exams Timeline' tab for upcoming assessments, the 'Assessments Log' tab for instructor notes and marks, or 'Term Results' to download your final PDF report.": "छात्र डैशबोर्ड पर जाएं। चयनकर्ता मेनू के तहत, आगामी मूल्यांकन के लिए 'परीक्षा समयरेखा' टैब, प्रशिक्षक नोट्स और अंकों के लिए 'मूल्यांकन लॉग' टैब, या अपनी अंतिम पीडीएफ रिपोर्ट डाउनलोड करने के लिए 'सत्र परिणाम' की जांच करें।",
    "I am operating in offline mode. Please click one of the quick questions below, or try searching for keywords like 'attendance', 'fees', 'message', 'materials', or 'results'.": "मैं ऑफ़लाइन मोड में काम कर रहा हूँ। कृपया नीचे दिए गए त्वरित प्रश्नों में से किसी एक पर क्लिक करें, या 'उपस्थिति', 'शुल्क', 'संदेश', 'सामग्री' या 'परिणाम' जैसे कीवर्ड खोजने का प्रयास करें।",
    "Assistant searching FAQ files...": "सहायक अक्सर पूछे जाने वाले प्रश्नों की फ़ाइलें खोज रहा है...",
    "EduManage AI Support": "एडुमैनेज एआई सहायता",
    "Offline Assistant": "ऑफ़लाइन सहायक",
    "Quick Questions": "त्वरित प्रश्न",
    "Ask about attendance, fees, messaging...": "उपस्थिति, शुल्क, संदेश के बारे में पूछें...",

    // New Subpages keys (Hindi)
    "Current semester": "वर्तमान सेमेस्टर",
    "94% average": "94% औसत",
    "Out of 32 students": "32 छात्रों में से",
    "Days Present": "उपस्थित दिन",
    "Days Absent": "अनुपस्थित दिन",
    "This month": "इस महीने",
    "Out of 21 school days": "21 स्कूल दिनों में से",
    "May 8 & May 20": "8 मई और 20 मई",
    "sessions": "सत्र",
    "Due by Jun 30": "30 जून तक देय",
    "This academic year": "इस शैक्षणिक वर्ष",
    "Jul 1": "1 जुलाई",
    "Quarterly tuition": "तिमाही ट्यूशन",
    "Q1 Tuition Fee": "Q1 ट्यूशन फीस",
    "Q2 Tuition Fee": "Q2 ट्यूशन फीस",
    "Library & Lab Fees": "पुस्तकालय और प्रयोगशाला शुल्क",
    "Q3 Tuition Fee": "Q3 ट्यूशन फीस",
    "Due": "देय",
    "Due: Jan 5": "देय तिथि: 5 जनवरी",
    "Due: Apr 3": "देय तिथि: 3 अप्रैल",
    "Due: Feb 15": "देय तिथि: 15 फ़रवरी",
    "Due: Jun 30": "देय तिथि: 30 जून",
    "Pay Outstanding Balance (₹320)": "बकाया राशि का भुगतान करें (₹320)",
    "Attendance Alert": "उपस्थिति चेतावनी",
    "Assignment Graded": "असाइनमेंट श्रेणीबद्ध",
    "Fee Reminder": "शुल्क अनुस्मारक",
    "Teacher Message": "शिक्षक संदेश",
    "{student} was marked absent on May 20 in Calculus BC.": "कैलकुलस बीसी में 20 मई को {student} को अनुपस्थित चिह्नित किया गया था।",
    "{student} received 94% on the Chemistry Lab report.": "रसायन विज्ञान प्रयोगशाला रिपोर्ट में {student} ने 94% प्राप्त किए।",
    "Q3 tuition fee of ₹320 is due by June 30.": "₹320 की Q3 ट्यूशन फीस 30 जून तक देय है।",
    'Prof. Miller: "{student} has been doing exceptionally well in physics!"': "प्रो. मिलर: \"{student} भौतिकी में असाधारण रूप से अच्छा प्रदर्शन कर रहा है!\"",
    "2 days ago": "2 दिन पहले",
    "3 days ago": "3 दिन पहले",
    "5 days ago": "5 दिन पहले",
    "1 week ago": "1 सप्ताह पहले",
    "Parent / Guardian": "अभिभावक / संरक्षक",
    "Linked Student": "लिंक किया गया छात्र",
    "Student Grade": "छात्र ग्रेड",
    "11th Grade": "11वीं कक्षा",
    "Track {student}'s performance across subjects.": "{student} के प्रदर्शन को सभी विषयों में ट्रैक करें।",
    "Monitor {student}'s daily attendance records.": "{student} के दैनिक उपस्थिति रिकॉर्ड की निगरानी करें।",
    "Across all courses": "सभी पाठ्यक्रमों में",
    "Course completed": "पाठ्यक्रम पूरा हुआ",
    "Advanced Physics": "उन्नत भौतिकी",
    "Calculus BC": "कैलकुलस बीसी",
    "Chemistry Honors": "रसायन विज्ञान ऑनर्स",
    "AP Literature": "एपी साहित्य",
    "Quantum Mechanics": "क्वांटम यांत्रिकी",
    "Rotational Dynamics": "घूर्णन गतिशीलता",
    "Organic Chemistry": "कार्बनिक रसायन विज्ञान",
    "Quantum Dynamics": "क्वांटम गतिशीलता",
    "Physics Mechanics": "भौतिकी यांत्रिकी",
    "Due Jun 10": "देय 10 जून",
    "Due Jun 12": "देय 12 जून",
    "Due Jun 6": "देय 6 जून",
    "Due this week": "इस सप्ताह देय",
    "Awaiting grades": "ग्रेड की प्रतीक्षा है",
    "This semester": "इस सेमेस्टर",
    "Rotational Kinematics Essay": "घूर्णन गतिकी निबंध",
    "Integral Calculus Problem Set": "समाकलन गणित समस्या सेट",
    "Titration Lab Report": "अनुमापन प्रयोगशाला रिपोर्ट",
    "Physics": "भौतिकी",
    "Chemistry": "रसायन विज्ञान",
    "Out of 21 sessions": "21 सत्रों में से",
    "sessions attended": "उपस्थित सत्र",
    "Out of 4.0": "4.0 में से",
    "91% average": "91% औसत",
    "Physics Mid-Term": "भौतिकी मध्यावधि",
    "Calculus Unit Test 3": "कैलकुलस यूनिट टेस्ट 3",
    "Chemistry Lab Practical": "रसायन विज्ञान प्रयोगशाला व्यावहारिक",
    "Literature Essay Exam": "साहित्य निबंध परीक्षा",
    "Student • 11th Grade": "छात्र • 11वीं कक्षा",
    "4 Subjects": "4 विषय",
    "#4 of 32": "32 में से 4वां",
    "Total Students": "कुल छात्र",
    "Across all sections": "सभी वर्गों में",
    "Physics – Studio Hall 2": "भौतिकी - स्टूडियो हॉल 2",
    "Monday": "सोमवार",
    "Tuesday": "मंगलवार",
    "Thursday": "गुरुवार",
    "Studio Hall 2": "स्टूडियो हॉल 2",
    "Lab Block 3": "लैब ब्लॉक 3",
    "Studio Hall 1": "स्टूडियो हॉल 1",
    "{count} Students": "{count} छात्र",
    "Today's Sessions": "आज के सत्र",
    "Sessions scheduled today": "आज निर्धारित सत्र",
    "Avg Attendance": "औसत उपस्थिति",
    "Last 30 days": "पिछले 30 दिन",
    "Absent Today": "आज अनुपस्थित",
    "Out of 20 students": "20 छात्रों में से",
    "Present": "उपस्थित",
    "Absent": "अनुपस्थित",
    "Active Assignments": "सक्रिय असाइनमेंट",
    "Currently assigned": "वर्तमान में आवंटित",
    "Submissions to grade": "मूल्यांकन के लिए सबमिशन",
    "Graded This Week": "इस सप्ताह श्रेणीबद्ध",
    "Completed evaluations": "पूरा हुआ मूल्यांकन",
    "Rotational Force Vector Essays": "घूर्णन बल वेक्टर निबंध",
    "Quantum State Functions": "क्वांटम अवस्था फलन",
    "Electromagnetic Induction Report": "विद्युत चुम्बकीय प्रेरण रिपोर्ट",
    "Top Performer": "सर्वश्रेष्ठ प्रदर्शन करने वाला",
    "Average 94.5%": "औसत 94.5%",
    "Class Average": "कक्षा का औसत",
    "All subjects": "सभी विषय",
    "Below 65% threshold": "65% सीमा से नीचे",
    "Subject": "विषय",
    "8 Years": "8 वर्ष",
    "28 Active": "28 सक्रिय",
    "View your scheduled sessions and timetable.": "अपने निर्धारित सत्र और समय सारिणी देखें।",
    "Mark and track student attendance for your classes.": "अपनी कक्षाओं के लिए छात्रों की उपस्थिति दर्ज करें और ट्रैक करें।",
    "Manage assignment submissions and evaluations.": "असाइनमेंट सबमिशन और मूल्यांकन प्रबंधित करें।",
    "Track academic progress across your students.": "अपने छात्रों की शैक्षणिक प्रगति को ट्रैक करें।",
    "View and update your faculty profile details.": "अपने फैकल्टी प्रोफाइल विवरण देखें और अपडेट करें।",
    "Faculty": "संकाय",
    "All academic courses and their assigned tutors": "सभी शैक्षणिक पाठ्यक्रम और उनके आवंटित ट्यूटर",
    "Course": "पाठ्यक्रम",
    "Students": "छात्र",
    "Schedule": "अनुसूची",
    "Level": "स्तर",
    "Status": "स्थिति",
    "Upcoming": "आगामी",
    "Draft": "ड्राफ्ट",
    "Total Collected": "कुल एकत्रित",
    "Outstanding": "बकाया",
    "Total Invoices": "कुल चालान",
    "Overdue": "विलंबित",
    "{count} overdue invoice(s) require immediate attention. Total outstanding: ": "{count} विलंबित चालान(ओं) पर तत्काल ध्यान देने की आवश्यकता है। कुल बकाया: ",
    "Invoice": "चालान",
    "Amount": "राशि",
    "Paid Date": "भुगतान की तिथि",
    "Not paid": "भुगतान नहीं किया",
    "Loading payment records...": "भुगतान रिकॉर्ड लोड किया जा रहा है...",
    "System Reports": "सिस्टम रिपोर्ट",
    "Generate and export academic, financial and operational reports.": "शैक्षणिक, वित्तीय और परिचालन रिपोर्ट उत्पन्न और निर्यात करें।",
    "System Configuration": "सिस्टम कॉन्फ़िगरेशन",
    "Adjust portal-wide settings, access control, and integrations.": "पोर्टल-व्यापी सेटिंग्स, एक्सेस नियंत्रण और एकीकरण समायोजित करें।",
    "Course Management": "पाठ्यक्रम प्रबंधन",
    "Fees & Billing": "शुल्क और बिलिंग",
    "Analytics & Reports": "विश्लेषण और रिपोर्ट",
    "Platform Settings": "प्लेटफ़ॉर्म सेटिंग्स",
    "View, add, edit and manage student enrollment records.": "छात्र नामांकन रिकॉर्ड देखें, जोड़ें, संपादित करें और प्रबंधित करें।",
    "Manage teaching faculty, subjects, and class assignments.": "शिक्षण संकाय, विषयों और कक्षा असाइनमेंट प्रबंधित करें।",
    "View and manage guardian accounts linked to students.": "छात्रों से जुड़े अभिभावक खातों को देखें और प्रबंधित करें।",
    "Create, assign, and manage academic courses and curricula.": "शैक्षणिक पाठ्यक्रम और पाठ्यक्रम बनाएं, असाइन करें और प्रबंधित करें।",
    "Track and manage tuition payments, invoices, and overdue dues.": "ट्यूशन भुगतान, चालान और बकाया राशि को ट्रैक और प्रबंधित करें।",
    "Generate performance, financial, and attendance reports.": "प्रदर्शन, वित्तीय और उपस्थिति रिपोर्ट उत्पन्न करें।",
    "Configure global options, security policies, and integrations.": "वैश्विक विकल्प, सुरक्षा नीतियां और एकीकरण कॉन्फ़िगर करें।",
    "View, add, edit, and delete guardian accounts linked to students.": "छात्रों से जुड़े अभिभावक खातों को देखें, जोड़ें, संपादित करें और हटाएं।",
    "Unregistered Parents Detected": "अपरिष्कृत अभिभावक पाए गए",
    "{count} parent phone(s) in the database have no portal account yet. Use \"Add Parent\" and enter the linked phone number to register them.": "डेटाबेस में {count} अभिभावक फोन नंबर(ओं) का अभी तक कोई पोर्टल खाता नहीं है। उन्हें पंजीकृत करने के लिए \"अभावक जोड़ें\" का उपयोग करें और लिंक किए गए फोन नंबर दर्ज करें।",
    "{count} parent record(s) — click a row to view linked students": "अभिभावक रिकॉर्ड — लिंक किए गए छात्रों को देखने के लिए एक पंक्ति पर क्लिक करें",
    "Add New Parent": "नया अभिभावक जोड़ें",
    "Edit Parent": "अभिभावक विवरण संपादित करें",
    "Create a guardian portal account": "अभिभावक पोर्टल खाता बनाएं",
    "Update guardian details": "अभिभावक विवरण अपडेट करें",
    "First Name *": "पहला नाम *",
    "Last Name *": "उपनाम *",
    "Email Address": "ईमेल पता",
    "Phone Number * ": "फ़ोन नंबर * ",
    "used to link students": "छात्रों को जोड़ने के लिए",
    "Auto-generated if left empty": "खाली छोड़ने पर स्वतः उत्पन्न",
    "Password *": "पासवर्ड *",
    "Min. 6 characters": "न्यूनतम 6 अक्षर",
    "Processing...": "प्रक्रिया जारी है...",
    "Create Parent Account": "अभिभावक खाता बनाएं",
    "Delete Parent Account": "अभिभावक खाता हटाएं",
    "Are you sure you want to delete": "क्या आप वाकई हटाना चाहते हैं",
    "This action cannot be undone.": "यह क्रिया पूर्ववत नहीं की जा सकती।",
    "{count} linked student(s) will lose their guardian link.": "{count} लिंक किए गए छात्र(ओं) का अपने अभिभावक से लिंक टूट जाएगा।",
    "Loading from database...": "डेटाबेस से लोड हो रहा है...",
    "Failed to load data": "डेटा लोड करने में विफल",
    "Retry": "पुनः प्रयास करें",
    "No parent records found": "कोई अभिभावक रिकॉर्ड नहीं मिला",
    "Add your first parent account to get started.": "शुरू करने के लिए अपना पहला अभिभावक खाता जोड़ें।",
    "Add First Parent": "पहला अभिभावक जोड़ें",
    "{count} student(s)": "{count} छात्र",
    "{count} due": "{count} बकाया",
    "Linked Students ({count})": "लिंक किए गए छात्र ({count})",
    "No students currently linked to this phone number.": "इस फ़ोन नंबर से वर्तमान में कोई छात्र जुड़ा नहीं है।",
    "Parent account created successfully.": "अभिभावक खाता सफलतापूर्वक बनाया गया।",
    "Parent account updated successfully.": "अभिभावक खाता सफलतापूर्वक अपडेट किया गया।",
    "Something went wrong. Please try again.": "कुछ गलत हो गया। कृपया पुन: प्रयास करें।",
    "Parent account deleted successfully.": "अभिभावक खाता सफलतापूर्वक हटा दिया गया।",
    "Failed to delete parent.": "अभिभावक को हटाने में विफल।",
    "Unregistered": "अपरिष्कृत",
    "Registered": "पंजीकृत",
    "Failed to load parents": "अभिभावकों को लोड करने में विफल",
    "Back to Directory": "निर्देशिका पर वापस जाएं",
    "Edit Profile": "प्रोफ़ाइल संपादित करें",
    "Delete Faculty Record": "संकाय रिकॉर्ड हटाएं",
    "Faculty Contact Phone": "संकाय संपर्क फोन",
    "Academic Subject Area": "शैक्षणिक विषय क्षेत्र",
    "Primary teaching specialty honors": "प्राथमिक शिक्षण विशेषता सम्मान",
    "Subject Honors": "विषय सम्मान",
    "Assigned Courses": "आवंटित पाठ्यक्रम",
    "Active sections listed": "सक्रिय अनुभाग सूचीबद्ध",
    "No courses assigned.": "कोई पाठ्यक्रम आवंटित नहीं है।",
    "Cumulative presence statistics": "संचयी उपस्थिति आँकड़े",
    "Salary Status": "वेतन स्थिति",
    "Tutor payment ledger status": "शिक्षक भुगतान बहीखाता स्थिति",
    "Payment Status": "भुगतान स्थिति",
    "Credited": "जमा किया गया",
    "Active": "सक्रिय",
    "Inactive": "निष्क्रिय",
    "pending": "लंबित",
    "100% On Duty": "100% ड्यूटी पर",
    "+12% vs last term": "+12% पिछले सत्र की तुलना में",
    "Logged": "दर्ज किया गया",
    "Real-Time Sync": "वास्तविक समय सिंक",
    "Student registration loads across standard academic periods": "मानक शैक्षणिक अवधियों में छात्र पंजीकरण भार",
    "Primary Cohorts": "प्राथमिक समूह",
    "Tuition fees balance status across directory profiles": "निर्देशिका प्रोफाइलों में ट्यूशन फीस संतुलन की स्थिति",
    "Total": "कुल",
    "Paid (65%)": "भुगतान किया गया (65%)",
    "Pending (20%)": "लंबित (20%)",
    "Overdue (15%)": "अतिदेय (15%)",
    "New Enrollment Messages": "नए पंजीकरण संदेश",
    "Student Profile": "छात्र प्रोफ़ाइल",
    "Applied Course / Subject": "लागू पाठ्यक्रम / विषय",
    "Student Phone": "छात्र फोन",
    "Parent Phone": "अभिभावक फोन",
    "Actions": "कार्रवाई",
    "Awaiting Review": "समीक्षा की प्रतीक्षा में",
    "N/A": "लागू नहीं",
    "Accept": "स्वीकार करें",
    "Decline": "अस्वीकार करें",
    "Live database enrollment and transaction transcripts": "लाइव डेटाबेस पंजीकरण और लेनदेन प्रतिलेख",
    "Student Name": "छात्र का नाम",
    "Action Type": "कार्रवाई का प्रकार",
    "Detail": "विवरण",
    "Date & Time": "तारीख और समय",
    "Ledger balance:": "बहीखाता शेष:",
    "Student Academic Enrollment Directory": "छात्र शैक्षणिक पंजीकरण निर्देशिका",
    "Directly add new academic entries, edit status, or click student name to view detailed files.": "सीधे नई शैक्षणिक प्रविष्टियां जोड़ें, स्थिति संपादित करें, या विस्तृत फाइलें देखने के लिए छात्र के नाम पर क्लिक करें।",
    "Search name, course standard, phone...": "नाम, पाठ्यक्रम मानक, फोन खोजें...",
    "Add Student": "छात्र जोड़ें",
    "Contact Phone": "संपर्क फोन",
    "Linked Parent Phone": "लिंक्ड अभिभावक फोन",
    "Unlinked": "अनलिंक्ड",
    "No student records match search query parameters.": "खोज मानदंडों से मेल खाने वाला कोई छात्र रिकॉर्ड नहीं है।",
    "Certified Academic Faculty Directory": "प्रमाणित शैक्षणिक संकाय निर्देशिका",
    "Manage certified educators, courses assignations, or click tutor name to view detailed files.": "प्रमाणित शिक्षकों, पाठ्यक्रम असाइनमेंट का प्रबंधन करें, या विस्तृत फाइलें देखने के लिए शिक्षक के नाम पर क्लिक करें।",
    "Add Faculty Tutor": "संकाय शिक्षक जोड़ें",
    "Faculty Member": "संकाय सदस्य",
    "Primary Subject": "प्राथमिक विषय",
    "No tutors currently registered in database.": "वर्तमान में डेटाबेस में कोई शिक्षक पंजीकृत नहीं है।",
    "Edit Student Profile": "छात्र प्रोफ़ाइल संपादित करें",
    "Enroll New Student": "नया छात्र पंजीकृत करें",
    "Update registration database properties": "पंजीकरण डेटाबेस गुण अपडेट करें",
    "Register a new active student": "एक नया सक्रिय छात्र पंजीकृत करें",
    "Jane": "जेन",
    "Doe": "डो",
    "Email Address *": "ईमेल पता *",
    "Student Phone *": "छात्र फोन *",
    "10 digit number": "10 अंकों की संख्या",
    "Grade Standard *": "ग्रेड मानक *",
    "9th Grade": "नौवीं कक्षा",
    "10th Grade": "दसवीं कक्षा",
    "12th Grade": "बारहवीं कक्षा",
    "Course Subject *": "पाठ्यक्रम विषय *",
    "Enrollment Status *": "पंजीकरण स्थिति *",
    "student123": "student123",
    "Save Student Changes": "छात्र परिवर्तन सहेजें",
    "Edit Tutor Profile": "शिक्षक प्रोफ़ाइल संपादित करें",
    "Register New Tutor": "नया शिक्षक पंजीकृत करें",
    "Update academic faculty database records": "शैक्षणिक संकाय डेटाबेस रिकॉर्ड अपडेट करें",
    "Introduce a new certified educator": "एक नया प्रमाणित शिक्षक शामिल करें",
    "Albert": "अल्बर्ट",
    "Einstein": "आइंस्टीन",
    "Subject Specialty *": "विषय विशेषज्ञता *",
    "Relativity & Cosmology": "सापेक्षता और ब्रह्मांड विज्ञान",
    "Experience *": "अनुभव *",
    "e.g. 12 years": "उदा. 12 वर्ष",
    "Duty Status *": "कर्तव्य स्थिति *",
    "e.g. 96%": "उदा. 96%",
    "tutor123": "tutor123",
    "Save Tutor Changes": "शिक्षक परिवर्तन सहेजें",
    "Register Tutor": "शिक्षक पंजीकृत करें",
    "First name, last name, and student phone are required.": "पहला नाम, उपनाम और छात्र फोन आवश्यक हैं।",
    "Student phone number must be exactly 10 digits.": "छात्र फोन नंबर बिल्कुल 10 अंकों का होना चाहिए।",
    "Parent phone number must be exactly 10 digits.": "अभिभावक फोन नंबर बिल्कुल 10 अंकों का होना चाहिए।",
    "Password is required.": "पासवर्ड आवश्यक है।",
    "Successfully updated student {name}": "छात्र {name} को सफलतापूर्वक अपडेट किया गया",
    "Successfully enrolled student {name}": "छात्र {name} को सफलतापूर्वक पंजीकृत किया गया",
    "Operation failed.": "ऑपरेशन विफल रहा।",
    "First name, last name, email, and tutor phone are required.": "पहला नाम, उपनाम, ईमेल और शिक्षक फोन आवश्यक हैं।",
    "Tutor phone number must be exactly 10 digits.": "शिक्षक फोन नंबर बिल्कुल 10 अंकों का होना चाहिए।",
    "Successfully updated tutor Prof. {first} {last}": "शिक्षक प्रो. {first} {last} को सफलतापूर्वक अपडेट किया गया",
    "Successfully added tutor Prof. {first} {last}": "शिक्षक प्रो. {first} {last} को सफलतापूर्वक जोड़ा गया",
    "Are you sure you want to delete student {name}? This will permanently remove their profile and bills.": "क्या आप वाकई छात्र {name} को हटाना चाहते हैं? इससे उनका प्रोफ़ाइल और बिल स्थायी रूप से हट जाएंगे।",
    "Deleted student {name}": "छात्र {name} को हटा दिया गया",
    "Delete student failed.": "छात्र को हटाना विफल रहा।",
    "Are you sure you want to delete tutor {name}? This will permanently remove their profile.": "क्या आप वाकई शिक्षक {name} को हटाना चाहते हैं? इससे उनका प्रोफ़ाइल स्थायी रूप से हट जाएगा।",
    "Deleted tutor {name}": "शिक्षक {name} को हटा दिया गया",
    "Delete tutor failed.": "शिक्षक को हटाना विफल रहा।",
    "Failed to fetch student details.": "छात्र विवरण प्राप्त करने में विफल।",
    "Failed to fetch tutor details.": "शिक्षक विवरण प्राप्त करने में विफल।",
    "Are you sure you want to decline and delete {name}'s registry?": "क्या आप वाकई {name} के पंजीकरण को अस्वीकार और हटाना चाहते हैं?",
    "Declined {name}": "{name} को अस्वीकार कर दिया गया",
    "Decline failed.": "अस्वीकार करना विफल रहा。"
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const cached = localStorage.getItem('edumanage_lang');
    return (cached as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('edumanage_lang', lang);
  };

  const t = (key: string): string => {
    const langDict = translations[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    return key; // Default fallback to English key itself
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
